# Flyway Configuration File for AOCS Project
flyway.url=jdbc:postgresql://localhost:5432/aocs_db
flyway.user=krish
flyway.password=
flyway.schemas=public
flyway.defaultSchema=public
flyway.locations=filesystem:db/migration
flyway.cleanDisabled=false
