-- ============================================================
-- AIRPORT OPERATIONS COORDINATION SYSTEM (AOCS)
-- Sample Seed Dataset (600+ Unique Rows: 60% National / 40% Intl)
-- Author: Krishna Solanki & AOCS Engineering Team
-- ============================================================

-- 1. ROLES
INSERT INTO roles (role_name) VALUES ('ROLE_ADMIN') ON CONFLICT (role_name) DO NOTHING;
INSERT INTO roles (role_name) VALUES ('ROLE_SUPERVISOR') ON CONFLICT (role_name) DO NOTHING;
INSERT INTO roles (role_name) VALUES ('ROLE_GROUND_CREW') ON CONFLICT (role_name) DO NOTHING;
INSERT INTO roles (role_name) VALUES ('ROLE_ATC') ON CONFLICT (role_name) DO NOTHING;
INSERT INTO roles (role_name) VALUES ('ROLE_DISPATCH') ON CONFLICT (role_name) DO NOTHING;

-- 2. DEPARTMENTS
INSERT INTO departments (department_name) VALUES ('Flight Dispatch & Navigation') ON CONFLICT (department_name) DO NOTHING;
INSERT INTO departments (department_name) VALUES ('Air Traffic Control (ATC)') ON CONFLICT (department_name) DO NOTHING;
INSERT INTO departments (department_name) VALUES ('Ground Handling & Turnaround') ON CONFLICT (department_name) DO NOTHING;
INSERT INTO departments (department_name) VALUES ('Refueling & Fuel Quality Ops') ON CONFLICT (department_name) DO NOTHING;
INSERT INTO departments (department_name) VALUES ('Cabin Cleaning & Sanitation') ON CONFLICT (department_name) DO NOTHING;
INSERT INTO departments (department_name) VALUES ('Cargo & Freight Logistics') ON CONFLICT (department_name) DO NOTHING;
INSERT INTO departments (department_name) VALUES ('Passenger Services & Terminal Ops') ON CONFLICT (department_name) DO NOTHING;
INSERT INTO departments (department_name) VALUES ('Airfield Security & Audit Control') ON CONFLICT (department_name) DO NOTHING;

-- 3. USERS (50)
INSERT INTO users (user_id, username, name, role_id, department_id) VALUES (1, 'aarav.sharma1', 'Aarav Sharma', 2, 2) ON CONFLICT DO NOTHING;
INSERT INTO user_phone_numbers (user_id, phone_number) VALUES (1, '+919800000001') ON CONFLICT DO NOTHING;
INSERT INTO users (user_id, username, name, role_id, department_id) VALUES (2, 'vivaan.verma2', 'Vivaan Verma', 3, 3) ON CONFLICT DO NOTHING;
INSERT INTO user_phone_numbers (user_id, phone_number) VALUES (2, '+919800000002') ON CONFLICT DO NOTHING;
INSERT INTO users (user_id, username, name, role_id, department_id) VALUES (3, 'aditya.patel3', 'Aditya Patel', 4, 4) ON CONFLICT DO NOTHING;
INSERT INTO user_phone_numbers (user_id, phone_number) VALUES (3, '+919800000003') ON CONFLICT DO NOTHING;
INSERT INTO users (user_id, username, name, role_id, department_id) VALUES (4, 'vihaan.singh4', 'Vihaan Singh', 5, 5) ON CONFLICT DO NOTHING;
INSERT INTO user_phone_numbers (user_id, phone_number) VALUES (4, '+919800000004') ON CONFLICT DO NOTHING;
INSERT INTO users (user_id, username, name, role_id, department_id) VALUES (5, 'arjun.kumar5', 'Arjun Kumar', 1, 6) ON CONFLICT DO NOTHING;
INSERT INTO user_phone_numbers (user_id, phone_number) VALUES (5, '+919800000005') ON CONFLICT DO NOTHING;
INSERT INTO users (user_id, username, name, role_id, department_id) VALUES (6, 'sai.gupta6', 'Sai Gupta', 2, 7) ON CONFLICT DO NOTHING;
INSERT INTO user_phone_numbers (user_id, phone_number) VALUES (6, '+919800000006') ON CONFLICT DO NOTHING;
INSERT INTO users (user_id, username, name, role_id, department_id) VALUES (7, 'reyansh.rao7', 'Reyansh Rao', 3, 8) ON CONFLICT DO NOTHING;
INSERT INTO user_phone_numbers (user_id, phone_number) VALUES (7, '+919800000007') ON CONFLICT DO NOTHING;
INSERT INTO users (user_id, username, name, role_id, department_id) VALUES (8, 'ayaan.joshi8', 'Ayaan Joshi', 4, 1) ON CONFLICT DO NOTHING;
INSERT INTO user_phone_numbers (user_id, phone_number) VALUES (8, '+919800000008') ON CONFLICT DO NOTHING;
INSERT INTO users (user_id, username, name, role_id, department_id) VALUES (9, 'krishna.mehta9', 'Krishna Mehta', 5, 2) ON CONFLICT DO NOTHING;
INSERT INTO user_phone_numbers (user_id, phone_number) VALUES (9, '+919800000009') ON CONFLICT DO NOTHING;
INSERT INTO users (user_id, username, name, role_id, department_id) VALUES (10, 'ishaan.shah10', 'Ishaan Shah', 1, 3) ON CONFLICT DO NOTHING;
INSERT INTO user_phone_numbers (user_id, phone_number) VALUES (10, '+919800000010') ON CONFLICT DO NOTHING;
INSERT INTO users (user_id, username, name, role_id, department_id) VALUES (11, 'dhruv.nair11', 'Dhruv Nair', 2, 4) ON CONFLICT DO NOTHING;
INSERT INTO user_phone_numbers (user_id, phone_number) VALUES (11, '+919800000011') ON CONFLICT DO NOTHING;
INSERT INTO users (user_id, username, name, role_id, department_id) VALUES (12, 'kabir.iyer12', 'Kabir Iyer', 3, 5) ON CONFLICT DO NOTHING;
INSERT INTO user_phone_numbers (user_id, phone_number) VALUES (12, '+919800000012') ON CONFLICT DO NOTHING;
INSERT INTO users (user_id, username, name, role_id, department_id) VALUES (13, 'ananya.chawla13', 'Ananya Chawla', 4, 6) ON CONFLICT DO NOTHING;
INSERT INTO user_phone_numbers (user_id, phone_number) VALUES (13, '+919800000013') ON CONFLICT DO NOTHING;
INSERT INTO users (user_id, username, name, role_id, department_id) VALUES (14, 'diya.deshmukh14', 'Diya Deshmukh', 5, 7) ON CONFLICT DO NOTHING;
INSERT INTO user_phone_numbers (user_id, phone_number) VALUES (14, '+919800000014') ON CONFLICT DO NOTHING;
INSERT INTO users (user_id, username, name, role_id, department_id) VALUES (15, 'pari.reddy15', 'Pari Reddy', 1, 8) ON CONFLICT DO NOTHING;
INSERT INTO user_phone_numbers (user_id, phone_number) VALUES (15, '+919800000015') ON CONFLICT DO NOTHING;
INSERT INTO users (user_id, username, name, role_id, department_id) VALUES (16, 'saanvi.solanki16', 'Saanvi Solanki', 2, 1) ON CONFLICT DO NOTHING;
INSERT INTO user_phone_numbers (user_id, phone_number) VALUES (16, '+919800000016') ON CONFLICT DO NOTHING;
INSERT INTO users (user_id, username, name, role_id, department_id) VALUES (17, 'riya.modi17', 'Riya Modi', 3, 2) ON CONFLICT DO NOTHING;
INSERT INTO user_phone_numbers (user_id, phone_number) VALUES (17, '+919800000017') ON CONFLICT DO NOTHING;
INSERT INTO users (user_id, username, name, role_id, department_id) VALUES (18, 'aadhya.tripathi18', 'Aadhya Tripathi', 4, 3) ON CONFLICT DO NOTHING;
INSERT INTO user_phone_numbers (user_id, phone_number) VALUES (18, '+919800000018') ON CONFLICT DO NOTHING;
INSERT INTO users (user_id, username, name, role_id, department_id) VALUES (19, 'neha.tikku19', 'Neha Tikku', 5, 4) ON CONFLICT DO NOTHING;
INSERT INTO user_phone_numbers (user_id, phone_number) VALUES (19, '+919800000019') ON CONFLICT DO NOTHING;
INSERT INTO users (user_id, username, name, role_id, department_id) VALUES (20, 'pooja.agarwal20', 'Pooja Agarwal', 1, 5) ON CONFLICT DO NOTHING;
INSERT INTO user_phone_numbers (user_id, phone_number) VALUES (20, '+919800000020') ON CONFLICT DO NOTHING;
INSERT INTO users (user_id, username, name, role_id, department_id) VALUES (21, 'rajesh.sharma21', 'Rajesh Sharma', 2, 6) ON CONFLICT DO NOTHING;
INSERT INTO user_phone_numbers (user_id, phone_number) VALUES (21, '+919800000021') ON CONFLICT DO NOTHING;
INSERT INTO users (user_id, username, name, role_id, department_id) VALUES (22, 'suresh.verma22', 'Suresh Verma', 3, 7) ON CONFLICT DO NOTHING;
INSERT INTO user_phone_numbers (user_id, phone_number) VALUES (22, '+919800000022') ON CONFLICT DO NOTHING;
INSERT INTO users (user_id, username, name, role_id, department_id) VALUES (23, 'vikram.patel23', 'Vikram Patel', 4, 8) ON CONFLICT DO NOTHING;
INSERT INTO user_phone_numbers (user_id, phone_number) VALUES (23, '+919800000023') ON CONFLICT DO NOTHING;
INSERT INTO users (user_id, username, name, role_id, department_id) VALUES (24, 'sunil.singh24', 'Sunil Singh', 5, 1) ON CONFLICT DO NOTHING;
INSERT INTO user_phone_numbers (user_id, phone_number) VALUES (24, '+919800000024') ON CONFLICT DO NOTHING;
INSERT INTO users (user_id, username, name, role_id, department_id) VALUES (25, 'amit.kumar25', 'Amit Kumar', 1, 2) ON CONFLICT DO NOTHING;
INSERT INTO user_phone_numbers (user_id, phone_number) VALUES (25, '+919800000025') ON CONFLICT DO NOTHING;
INSERT INTO users (user_id, username, name, role_id, department_id) VALUES (26, 'rahul.gupta26', 'Rahul Gupta', 2, 3) ON CONFLICT DO NOTHING;
INSERT INTO user_phone_numbers (user_id, phone_number) VALUES (26, '+919800000026') ON CONFLICT DO NOTHING;
INSERT INTO users (user_id, username, name, role_id, department_id) VALUES (27, 'priya.rao27', 'Priya Rao', 3, 4) ON CONFLICT DO NOTHING;
INSERT INTO user_phone_numbers (user_id, phone_number) VALUES (27, '+919800000027') ON CONFLICT DO NOTHING;
INSERT INTO users (user_id, username, name, role_id, department_id) VALUES (28, 'sneha.joshi28', 'Sneha Joshi', 4, 5) ON CONFLICT DO NOTHING;
INSERT INTO user_phone_numbers (user_id, phone_number) VALUES (28, '+919800000028') ON CONFLICT DO NOTHING;
INSERT INTO users (user_id, username, name, role_id, department_id) VALUES (29, 'karan.mehta29', 'Karan Mehta', 5, 6) ON CONFLICT DO NOTHING;
INSERT INTO user_phone_numbers (user_id, phone_number) VALUES (29, '+919800000029') ON CONFLICT DO NOTHING;
INSERT INTO users (user_id, username, name, role_id, department_id) VALUES (30, 'gaurav.shah30', 'Gaurav Shah', 1, 7) ON CONFLICT DO NOTHING;
INSERT INTO user_phone_numbers (user_id, phone_number) VALUES (30, '+919800000030') ON CONFLICT DO NOTHING;
INSERT INTO users (user_id, username, name, role_id, department_id) VALUES (31, 'john.smith31', 'John Smith', 2, 8) ON CONFLICT DO NOTHING;
INSERT INTO user_phone_numbers (user_id, phone_number) VALUES (31, '+14150000031') ON CONFLICT DO NOTHING;
INSERT INTO users (user_id, username, name, role_id, department_id) VALUES (32, 'michael.johnson32', 'Michael Johnson', 3, 1) ON CONFLICT DO NOTHING;
INSERT INTO user_phone_numbers (user_id, phone_number) VALUES (32, '+14150000032') ON CONFLICT DO NOTHING;
INSERT INTO users (user_id, username, name, role_id, department_id) VALUES (33, 'david.williams33', 'David Williams', 4, 2) ON CONFLICT DO NOTHING;
INSERT INTO user_phone_numbers (user_id, phone_number) VALUES (33, '+14150000033') ON CONFLICT DO NOTHING;
INSERT INTO users (user_id, username, name, role_id, department_id) VALUES (34, 'james.brown34', 'James Brown', 5, 3) ON CONFLICT DO NOTHING;
INSERT INTO user_phone_numbers (user_id, phone_number) VALUES (34, '+14150000034') ON CONFLICT DO NOTHING;
INSERT INTO users (user_id, username, name, role_id, department_id) VALUES (35, 'robert.jones35', 'Robert Jones', 1, 4) ON CONFLICT DO NOTHING;
INSERT INTO user_phone_numbers (user_id, phone_number) VALUES (35, '+14150000035') ON CONFLICT DO NOTHING;
INSERT INTO users (user_id, username, name, role_id, department_id) VALUES (36, 'emily.garcia36', 'Emily Garcia', 2, 5) ON CONFLICT DO NOTHING;
INSERT INTO user_phone_numbers (user_id, phone_number) VALUES (36, '+14150000036') ON CONFLICT DO NOTHING;
INSERT INTO users (user_id, username, name, role_id, department_id) VALUES (37, 'sarah.miller37', 'Sarah Miller', 3, 6) ON CONFLICT DO NOTHING;
INSERT INTO user_phone_numbers (user_id, phone_number) VALUES (37, '+14150000037') ON CONFLICT DO NOTHING;
INSERT INTO users (user_id, username, name, role_id, department_id) VALUES (38, 'jessica.davis38', 'Jessica Davis', 4, 7) ON CONFLICT DO NOTHING;
INSERT INTO user_phone_numbers (user_id, phone_number) VALUES (38, '+14150000038') ON CONFLICT DO NOTHING;
INSERT INTO users (user_id, username, name, role_id, department_id) VALUES (39, 'daniel.rodriguez39', 'Daniel Rodriguez', 5, 8) ON CONFLICT DO NOTHING;
INSERT INTO user_phone_numbers (user_id, phone_number) VALUES (39, '+14150000039') ON CONFLICT DO NOTHING;
INSERT INTO users (user_id, username, name, role_id, department_id) VALUES (40, 'matthew.martinez40', 'Matthew Martinez', 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO user_phone_numbers (user_id, phone_number) VALUES (40, '+14150000040') ON CONFLICT DO NOTHING;
INSERT INTO users (user_id, username, name, role_id, department_id) VALUES (41, 'alex.wilson41', 'Alex Wilson', 2, 2) ON CONFLICT DO NOTHING;
INSERT INTO user_phone_numbers (user_id, phone_number) VALUES (41, '+14150000041') ON CONFLICT DO NOTHING;
INSERT INTO users (user_id, username, name, role_id, department_id) VALUES (42, 'christopher.anderson42', 'Christopher Anderson', 3, 3) ON CONFLICT DO NOTHING;
INSERT INTO user_phone_numbers (user_id, phone_number) VALUES (42, '+14150000042') ON CONFLICT DO NOTHING;
INSERT INTO users (user_id, username, name, role_id, department_id) VALUES (43, 'sophia.taylor43', 'Sophia Taylor', 4, 4) ON CONFLICT DO NOTHING;
INSERT INTO user_phone_numbers (user_id, phone_number) VALUES (43, '+14150000043') ON CONFLICT DO NOTHING;
INSERT INTO users (user_id, username, name, role_id, department_id) VALUES (44, 'emma.thomas44', 'Emma Thomas', 5, 5) ON CONFLICT DO NOTHING;
INSERT INTO user_phone_numbers (user_id, phone_number) VALUES (44, '+14150000044') ON CONFLICT DO NOTHING;
INSERT INTO users (user_id, username, name, role_id, department_id) VALUES (45, 'olivia.moore45', 'Olivia Moore', 1, 6) ON CONFLICT DO NOTHING;
INSERT INTO user_phone_numbers (user_id, phone_number) VALUES (45, '+14150000045') ON CONFLICT DO NOTHING;
INSERT INTO users (user_id, username, name, role_id, department_id) VALUES (46, 'liam.jackson46', 'Liam Jackson', 2, 7) ON CONFLICT DO NOTHING;
INSERT INTO user_phone_numbers (user_id, phone_number) VALUES (46, '+14150000046') ON CONFLICT DO NOTHING;
INSERT INTO users (user_id, username, name, role_id, department_id) VALUES (47, 'noah.martin47', 'Noah Martin', 3, 8) ON CONFLICT DO NOTHING;
INSERT INTO user_phone_numbers (user_id, phone_number) VALUES (47, '+14150000047') ON CONFLICT DO NOTHING;
INSERT INTO users (user_id, username, name, role_id, department_id) VALUES (48, 'lucas.lee48', 'Lucas Lee', 4, 1) ON CONFLICT DO NOTHING;
INSERT INTO user_phone_numbers (user_id, phone_number) VALUES (48, '+14150000048') ON CONFLICT DO NOTHING;
INSERT INTO users (user_id, username, name, role_id, department_id) VALUES (49, 'ethan.perez49', 'Ethan Perez', 5, 2) ON CONFLICT DO NOTHING;
INSERT INTO user_phone_numbers (user_id, phone_number) VALUES (49, '+14150000049') ON CONFLICT DO NOTHING;
INSERT INTO users (user_id, username, name, role_id, department_id) VALUES (50, 'oliver.thompson50', 'Oliver Thompson', 1, 3) ON CONFLICT DO NOTHING;
INSERT INTO user_phone_numbers (user_id, phone_number) VALUES (50, '+14150000050') ON CONFLICT DO NOTHING;

-- 5. AIRCRAFT (40)
INSERT INTO aircraft (aircraft_id, registration_number) VALUES (1, 'VT-ABD') ON CONFLICT DO NOTHING;
INSERT INTO aircraft (aircraft_id, registration_number) VALUES (2, 'VT-ACG') ON CONFLICT DO NOTHING;
INSERT INTO aircraft (aircraft_id, registration_number) VALUES (3, 'VT-ADJ') ON CONFLICT DO NOTHING;
INSERT INTO aircraft (aircraft_id, registration_number) VALUES (4, 'VT-AEM') ON CONFLICT DO NOTHING;
INSERT INTO aircraft (aircraft_id, registration_number) VALUES (5, 'VT-AFP') ON CONFLICT DO NOTHING;
INSERT INTO aircraft (aircraft_id, registration_number) VALUES (6, 'VT-AGS') ON CONFLICT DO NOTHING;
INSERT INTO aircraft (aircraft_id, registration_number) VALUES (7, 'VT-AHV') ON CONFLICT DO NOTHING;
INSERT INTO aircraft (aircraft_id, registration_number) VALUES (8, 'VT-AIY') ON CONFLICT DO NOTHING;
INSERT INTO aircraft (aircraft_id, registration_number) VALUES (9, 'VT-AJB') ON CONFLICT DO NOTHING;
INSERT INTO aircraft (aircraft_id, registration_number) VALUES (10, 'VT-AKE') ON CONFLICT DO NOTHING;
INSERT INTO aircraft (aircraft_id, registration_number) VALUES (11, 'VT-ALH') ON CONFLICT DO NOTHING;
INSERT INTO aircraft (aircraft_id, registration_number) VALUES (12, 'VT-AMK') ON CONFLICT DO NOTHING;
INSERT INTO aircraft (aircraft_id, registration_number) VALUES (13, 'VT-ANN') ON CONFLICT DO NOTHING;
INSERT INTO aircraft (aircraft_id, registration_number) VALUES (14, 'VT-AOQ') ON CONFLICT DO NOTHING;
INSERT INTO aircraft (aircraft_id, registration_number) VALUES (15, 'VT-APT') ON CONFLICT DO NOTHING;
INSERT INTO aircraft (aircraft_id, registration_number) VALUES (16, 'VT-AQW') ON CONFLICT DO NOTHING;
INSERT INTO aircraft (aircraft_id, registration_number) VALUES (17, 'VT-ARZ') ON CONFLICT DO NOTHING;
INSERT INTO aircraft (aircraft_id, registration_number) VALUES (18, 'VT-ASC') ON CONFLICT DO NOTHING;
INSERT INTO aircraft (aircraft_id, registration_number) VALUES (19, 'VT-ATF') ON CONFLICT DO NOTHING;
INSERT INTO aircraft (aircraft_id, registration_number) VALUES (20, 'VT-AUI') ON CONFLICT DO NOTHING;
INSERT INTO aircraft (aircraft_id, registration_number) VALUES (21, 'VT-AVL') ON CONFLICT DO NOTHING;
INSERT INTO aircraft (aircraft_id, registration_number) VALUES (22, 'VT-AWO') ON CONFLICT DO NOTHING;
INSERT INTO aircraft (aircraft_id, registration_number) VALUES (23, 'VT-AXR') ON CONFLICT DO NOTHING;
INSERT INTO aircraft (aircraft_id, registration_number) VALUES (24, 'VT-AYU') ON CONFLICT DO NOTHING;
INSERT INTO aircraft (aircraft_id, registration_number) VALUES (25, 'A6-E25A') ON CONFLICT DO NOTHING;
INSERT INTO aircraft (aircraft_id, registration_number) VALUES (26, 'G-X26A') ON CONFLICT DO NOTHING;
INSERT INTO aircraft (aircraft_id, registration_number) VALUES (27, '9V-S27A') ON CONFLICT DO NOTHING;
INSERT INTO aircraft (aircraft_id, registration_number) VALUES (28, 'N728A') ON CONFLICT DO NOTHING;
INSERT INTO aircraft (aircraft_id, registration_number) VALUES (29, 'A6-E29A') ON CONFLICT DO NOTHING;
INSERT INTO aircraft (aircraft_id, registration_number) VALUES (30, 'G-X30A') ON CONFLICT DO NOTHING;
INSERT INTO aircraft (aircraft_id, registration_number) VALUES (31, '9V-S31A') ON CONFLICT DO NOTHING;
INSERT INTO aircraft (aircraft_id, registration_number) VALUES (32, 'N732A') ON CONFLICT DO NOTHING;
INSERT INTO aircraft (aircraft_id, registration_number) VALUES (33, 'A6-E33A') ON CONFLICT DO NOTHING;
INSERT INTO aircraft (aircraft_id, registration_number) VALUES (34, 'G-X34A') ON CONFLICT DO NOTHING;
INSERT INTO aircraft (aircraft_id, registration_number) VALUES (35, '9V-S35A') ON CONFLICT DO NOTHING;
INSERT INTO aircraft (aircraft_id, registration_number) VALUES (36, 'N736A') ON CONFLICT DO NOTHING;
INSERT INTO aircraft (aircraft_id, registration_number) VALUES (37, 'A6-E37A') ON CONFLICT DO NOTHING;
INSERT INTO aircraft (aircraft_id, registration_number) VALUES (38, 'G-X38A') ON CONFLICT DO NOTHING;
INSERT INTO aircraft (aircraft_id, registration_number) VALUES (39, '9V-S39A') ON CONFLICT DO NOTHING;
INSERT INTO aircraft (aircraft_id, registration_number) VALUES (40, 'N740A') ON CONFLICT DO NOTHING;

-- 6. GATES (30)
INSERT INTO gates (gate_id, gate_number) VALUES (1, 'A01') ON CONFLICT DO NOTHING;
INSERT INTO gates (gate_id, gate_number) VALUES (2, 'A02') ON CONFLICT DO NOTHING;
INSERT INTO gates (gate_id, gate_number) VALUES (3, 'A03') ON CONFLICT DO NOTHING;
INSERT INTO gates (gate_id, gate_number) VALUES (4, 'A04') ON CONFLICT DO NOTHING;
INSERT INTO gates (gate_id, gate_number) VALUES (5, 'A05') ON CONFLICT DO NOTHING;
INSERT INTO gates (gate_id, gate_number) VALUES (6, 'A06') ON CONFLICT DO NOTHING;
INSERT INTO gates (gate_id, gate_number) VALUES (7, 'A07') ON CONFLICT DO NOTHING;
INSERT INTO gates (gate_id, gate_number) VALUES (8, 'A08') ON CONFLICT DO NOTHING;
INSERT INTO gates (gate_id, gate_number) VALUES (9, 'A09') ON CONFLICT DO NOTHING;
INSERT INTO gates (gate_id, gate_number) VALUES (10, 'A10') ON CONFLICT DO NOTHING;
INSERT INTO gates (gate_id, gate_number) VALUES (11, 'A11') ON CONFLICT DO NOTHING;
INSERT INTO gates (gate_id, gate_number) VALUES (12, 'A12') ON CONFLICT DO NOTHING;
INSERT INTO gates (gate_id, gate_number) VALUES (13, 'A13') ON CONFLICT DO NOTHING;
INSERT INTO gates (gate_id, gate_number) VALUES (14, 'A14') ON CONFLICT DO NOTHING;
INSERT INTO gates (gate_id, gate_number) VALUES (15, 'A15') ON CONFLICT DO NOTHING;
INSERT INTO gates (gate_id, gate_number) VALUES (16, 'A16') ON CONFLICT DO NOTHING;
INSERT INTO gates (gate_id, gate_number) VALUES (17, 'A17') ON CONFLICT DO NOTHING;
INSERT INTO gates (gate_id, gate_number) VALUES (18, 'A18') ON CONFLICT DO NOTHING;
INSERT INTO gates (gate_id, gate_number) VALUES (19, 'B01') ON CONFLICT DO NOTHING;
INSERT INTO gates (gate_id, gate_number) VALUES (20, 'B02') ON CONFLICT DO NOTHING;
INSERT INTO gates (gate_id, gate_number) VALUES (21, 'B03') ON CONFLICT DO NOTHING;
INSERT INTO gates (gate_id, gate_number) VALUES (22, 'B04') ON CONFLICT DO NOTHING;
INSERT INTO gates (gate_id, gate_number) VALUES (23, 'B05') ON CONFLICT DO NOTHING;
INSERT INTO gates (gate_id, gate_number) VALUES (24, 'B06') ON CONFLICT DO NOTHING;
INSERT INTO gates (gate_id, gate_number) VALUES (25, 'B07') ON CONFLICT DO NOTHING;
INSERT INTO gates (gate_id, gate_number) VALUES (26, 'B08') ON CONFLICT DO NOTHING;
INSERT INTO gates (gate_id, gate_number) VALUES (27, 'B09') ON CONFLICT DO NOTHING;
INSERT INTO gates (gate_id, gate_number) VALUES (28, 'B10') ON CONFLICT DO NOTHING;
INSERT INTO gates (gate_id, gate_number) VALUES (29, 'B11') ON CONFLICT DO NOTHING;
INSERT INTO gates (gate_id, gate_number) VALUES (30, 'B12') ON CONFLICT DO NOTHING;

-- 7. RUNWAYS (10)
INSERT INTO runways (runway_id, runway_code) VALUES (1, '09L') ON CONFLICT DO NOTHING;
INSERT INTO runways (runway_id, runway_code) VALUES (2, '09R') ON CONFLICT DO NOTHING;
INSERT INTO runways (runway_id, runway_code) VALUES (3, '27L') ON CONFLICT DO NOTHING;
INSERT INTO runways (runway_id, runway_code) VALUES (4, '27R') ON CONFLICT DO NOTHING;
INSERT INTO runways (runway_id, runway_code) VALUES (5, '10L') ON CONFLICT DO NOTHING;
INSERT INTO runways (runway_id, runway_code) VALUES (6, '10R') ON CONFLICT DO NOTHING;
INSERT INTO runways (runway_id, runway_code) VALUES (7, '28L') ON CONFLICT DO NOTHING;
INSERT INTO runways (runway_id, runway_code) VALUES (8, '28R') ON CONFLICT DO NOTHING;
INSERT INTO runways (runway_id, runway_code) VALUES (9, '14L') ON CONFLICT DO NOTHING;
INSERT INTO runways (runway_id, runway_code) VALUES (10, '32R') ON CONFLICT DO NOTHING;

-- 8. FLIGHTS (60)
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (1, 'AI101', 'SCHEDULED', 2, 2, 2, 2) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (2, '6E102', 'BOARDING', 3, 3, 3, 3) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (3, 'UK103', 'AIRBORNE', 4, 4, 4, 4) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (4, 'QP104', 'LANDED', 5, 5, 5, 5) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (5, 'SG105', 'DELAYED', 6, 6, 6, 6) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (6, 'AI106', 'CANCELLED', 7, 7, 7, 7) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (7, '6E107', 'SCHEDULED', 8, 8, 8, 8) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (8, 'UK108', 'BOARDING', 9, 9, 9, 1) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (9, 'QP109', 'AIRBORNE', 10, 10, 10, 2) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (10, 'SG110', 'LANDED', 11, 11, 1, 3) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (11, 'AI111', 'DELAYED', 12, 12, 2, 4) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (12, '6E112', 'CANCELLED', 13, 13, 3, 5) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (13, 'UK113', 'SCHEDULED', 14, 14, 4, 6) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (14, 'QP114', 'BOARDING', 15, 15, 5, 7) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (15, 'SG115', 'AIRBORNE', 16, 16, 6, 8) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (16, 'AI116', 'LANDED', 17, 17, 7, 1) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (17, '6E117', 'DELAYED', 18, 18, 8, 2) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (18, 'UK118', 'CANCELLED', 19, 19, 9, 3) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (19, 'QP119', 'SCHEDULED', 20, 20, 10, 4) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (20, 'SG120', 'BOARDING', 21, 21, 1, 5) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (21, 'AI121', 'AIRBORNE', 22, 22, 2, 6) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (22, '6E122', 'LANDED', 23, 23, 3, 7) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (23, 'UK123', 'DELAYED', 24, 24, 4, 8) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (24, 'QP124', 'CANCELLED', 1, 25, 5, 1) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (25, 'SG125', 'SCHEDULED', 2, 26, 6, 2) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (26, 'AI126', 'BOARDING', 3, 27, 7, 3) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (27, '6E127', 'AIRBORNE', 4, 28, 8, 4) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (28, 'UK128', 'LANDED', 5, 29, 9, 5) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (29, 'QP129', 'DELAYED', 6, 30, 10, 6) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (30, 'SG130', 'CANCELLED', 7, 1, 1, 7) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (31, 'AI131', 'SCHEDULED', 8, 2, 2, 8) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (32, '6E132', 'BOARDING', 9, 3, 3, 1) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (33, 'UK133', 'AIRBORNE', 10, 4, 4, 2) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (34, 'QP134', 'LANDED', 11, 5, 5, 3) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (35, 'SG135', 'DELAYED', 12, 6, 6, 4) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (36, 'AI136', 'CANCELLED', 13, 7, 7, 5) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (37, 'EK537', 'SCHEDULED', 25, 8, 8, 6) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (38, 'BA538', 'BOARDING', 26, 9, 9, 7) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (39, 'SQ539', 'AIRBORNE', 27, 10, 10, 8) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (40, 'QR540', 'LANDED', 28, 11, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (41, 'LH541', 'DELAYED', 29, 12, 2, 2) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (42, 'UA542', 'CANCELLED', 30, 13, 3, 3) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (43, 'EK543', 'SCHEDULED', 31, 14, 4, 4) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (44, 'BA544', 'BOARDING', 32, 15, 5, 5) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (45, 'SQ545', 'AIRBORNE', 33, 16, 6, 6) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (46, 'QR546', 'LANDED', 34, 17, 7, 7) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (47, 'LH547', 'DELAYED', 35, 18, 8, 8) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (48, 'UA548', 'CANCELLED', 36, 19, 9, 1) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (49, 'EK549', 'SCHEDULED', 37, 20, 10, 2) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (50, 'BA550', 'BOARDING', 38, 21, 1, 3) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (51, 'SQ551', 'AIRBORNE', 39, 22, 2, 4) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (52, 'QR552', 'LANDED', 40, 23, 3, 5) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (53, 'LH553', 'DELAYED', 25, 24, 4, 6) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (54, 'UA554', 'CANCELLED', 26, 25, 5, 7) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (55, 'EK555', 'SCHEDULED', 27, 26, 6, 8) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (56, 'BA556', 'BOARDING', 28, 27, 7, 1) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (57, 'SQ557', 'AIRBORNE', 29, 28, 8, 2) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (58, 'QR558', 'LANDED', 30, 29, 9, 3) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (59, 'LH559', 'DELAYED', 31, 30, 10, 4) ON CONFLICT DO NOTHING;
INSERT INTO flights (flight_id, flight_number, flight_status, aircraft_id, gate_id, runway_id, department_id) VALUES (60, 'UA560', 'CANCELLED', 32, 1, 1, 5) ON CONFLICT DO NOTHING;

-- 9. TASKS (120)
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (1, 'Catering & Galley Supply Loading', 'COMPLETED', 1, 2) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (2, 'Baggage & Freight Loading', 'BLOCKED', 1, 7) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (3, 'Avionics & Pre-flight Maintenance', 'PENDING', 2, 3) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (4, 'Cabin Cleaning & Decontamination', 'IN_PROGRESS', 2, 8) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (5, 'Aviation Refueling & Density Check', 'COMPLETED', 3, 4) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (6, 'Catering & Galley Supply Loading', 'BLOCKED', 3, 9) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (7, 'Baggage & Freight Loading', 'PENDING', 4, 5) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (8, 'Avionics & Pre-flight Maintenance', 'IN_PROGRESS', 4, 10) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (9, 'Cabin Cleaning & Decontamination', 'COMPLETED', 5, 6) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (10, 'Aviation Refueling & Density Check', 'BLOCKED', 5, 11) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (11, 'Catering & Galley Supply Loading', 'PENDING', 6, 7) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (12, 'Baggage & Freight Loading', 'IN_PROGRESS', 6, 12) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (13, 'Avionics & Pre-flight Maintenance', 'COMPLETED', 7, 8) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (14, 'Cabin Cleaning & Decontamination', 'BLOCKED', 7, 13) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (15, 'Aviation Refueling & Density Check', 'PENDING', 8, 9) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (16, 'Catering & Galley Supply Loading', 'IN_PROGRESS', 8, 14) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (17, 'Baggage & Freight Loading', 'COMPLETED', 9, 10) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (18, 'Avionics & Pre-flight Maintenance', 'BLOCKED', 9, 15) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (19, 'Cabin Cleaning & Decontamination', 'PENDING', 10, 11) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (20, 'Aviation Refueling & Density Check', 'IN_PROGRESS', 10, 16) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (21, 'Catering & Galley Supply Loading', 'COMPLETED', 11, 12) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (22, 'Baggage & Freight Loading', 'BLOCKED', 11, 17) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (23, 'Avionics & Pre-flight Maintenance', 'PENDING', 12, 13) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (24, 'Cabin Cleaning & Decontamination', 'IN_PROGRESS', 12, 18) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (25, 'Aviation Refueling & Density Check', 'COMPLETED', 13, 14) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (26, 'Catering & Galley Supply Loading', 'BLOCKED', 13, 19) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (27, 'Baggage & Freight Loading', 'PENDING', 14, 15) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (28, 'Avionics & Pre-flight Maintenance', 'IN_PROGRESS', 14, 20) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (29, 'Cabin Cleaning & Decontamination', 'COMPLETED', 15, 16) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (30, 'Aviation Refueling & Density Check', 'BLOCKED', 15, 21) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (31, 'Catering & Galley Supply Loading', 'PENDING', 16, 17) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (32, 'Baggage & Freight Loading', 'IN_PROGRESS', 16, 22) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (33, 'Avionics & Pre-flight Maintenance', 'COMPLETED', 17, 18) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (34, 'Cabin Cleaning & Decontamination', 'BLOCKED', 17, 23) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (35, 'Aviation Refueling & Density Check', 'PENDING', 18, 19) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (36, 'Catering & Galley Supply Loading', 'IN_PROGRESS', 18, 24) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (37, 'Baggage & Freight Loading', 'COMPLETED', 19, 20) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (38, 'Avionics & Pre-flight Maintenance', 'BLOCKED', 19, 25) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (39, 'Cabin Cleaning & Decontamination', 'PENDING', 20, 21) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (40, 'Aviation Refueling & Density Check', 'IN_PROGRESS', 20, 26) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (41, 'Catering & Galley Supply Loading', 'COMPLETED', 21, 22) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (42, 'Baggage & Freight Loading', 'BLOCKED', 21, 27) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (43, 'Avionics & Pre-flight Maintenance', 'PENDING', 22, 23) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (44, 'Cabin Cleaning & Decontamination', 'IN_PROGRESS', 22, 28) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (45, 'Aviation Refueling & Density Check', 'COMPLETED', 23, 24) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (46, 'Catering & Galley Supply Loading', 'BLOCKED', 23, 29) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (47, 'Baggage & Freight Loading', 'PENDING', 24, 25) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (48, 'Avionics & Pre-flight Maintenance', 'IN_PROGRESS', 24, 30) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (49, 'Cabin Cleaning & Decontamination', 'COMPLETED', 25, 26) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (50, 'Aviation Refueling & Density Check', 'BLOCKED', 25, 31) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (51, 'Catering & Galley Supply Loading', 'PENDING', 26, 27) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (52, 'Baggage & Freight Loading', 'IN_PROGRESS', 26, 32) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (53, 'Avionics & Pre-flight Maintenance', 'COMPLETED', 27, 28) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (54, 'Cabin Cleaning & Decontamination', 'BLOCKED', 27, 33) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (55, 'Aviation Refueling & Density Check', 'PENDING', 28, 29) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (56, 'Catering & Galley Supply Loading', 'IN_PROGRESS', 28, 34) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (57, 'Baggage & Freight Loading', 'COMPLETED', 29, 30) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (58, 'Avionics & Pre-flight Maintenance', 'BLOCKED', 29, 35) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (59, 'Cabin Cleaning & Decontamination', 'PENDING', 30, 31) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (60, 'Aviation Refueling & Density Check', 'IN_PROGRESS', 30, 36) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (61, 'Catering & Galley Supply Loading', 'COMPLETED', 31, 32) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (62, 'Baggage & Freight Loading', 'BLOCKED', 31, 37) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (63, 'Avionics & Pre-flight Maintenance', 'PENDING', 32, 33) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (64, 'Cabin Cleaning & Decontamination', 'IN_PROGRESS', 32, 38) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (65, 'Aviation Refueling & Density Check', 'COMPLETED', 33, 34) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (66, 'Catering & Galley Supply Loading', 'BLOCKED', 33, 39) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (67, 'Baggage & Freight Loading', 'PENDING', 34, 35) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (68, 'Avionics & Pre-flight Maintenance', 'IN_PROGRESS', 34, 40) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (69, 'Cabin Cleaning & Decontamination', 'COMPLETED', 35, 36) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (70, 'Aviation Refueling & Density Check', 'BLOCKED', 35, 41) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (71, 'Catering & Galley Supply Loading', 'PENDING', 36, 37) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (72, 'Baggage & Freight Loading', 'IN_PROGRESS', 36, 42) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (73, 'Avionics & Pre-flight Maintenance', 'COMPLETED', 37, 38) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (74, 'Cabin Cleaning & Decontamination', 'BLOCKED', 37, 43) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (75, 'Aviation Refueling & Density Check', 'PENDING', 38, 39) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (76, 'Catering & Galley Supply Loading', 'IN_PROGRESS', 38, 44) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (77, 'Baggage & Freight Loading', 'COMPLETED', 39, 40) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (78, 'Avionics & Pre-flight Maintenance', 'BLOCKED', 39, 45) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (79, 'Cabin Cleaning & Decontamination', 'PENDING', 40, 41) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (80, 'Aviation Refueling & Density Check', 'IN_PROGRESS', 40, 46) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (81, 'Catering & Galley Supply Loading', 'COMPLETED', 41, 42) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (82, 'Baggage & Freight Loading', 'BLOCKED', 41, 47) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (83, 'Avionics & Pre-flight Maintenance', 'PENDING', 42, 43) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (84, 'Cabin Cleaning & Decontamination', 'IN_PROGRESS', 42, 48) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (85, 'Aviation Refueling & Density Check', 'COMPLETED', 43, 44) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (86, 'Catering & Galley Supply Loading', 'BLOCKED', 43, 49) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (87, 'Baggage & Freight Loading', 'PENDING', 44, 45) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (88, 'Avionics & Pre-flight Maintenance', 'IN_PROGRESS', 44, 50) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (89, 'Cabin Cleaning & Decontamination', 'COMPLETED', 45, 46) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (90, 'Aviation Refueling & Density Check', 'BLOCKED', 45, 1) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (91, 'Catering & Galley Supply Loading', 'PENDING', 46, 47) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (92, 'Baggage & Freight Loading', 'IN_PROGRESS', 46, 2) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (93, 'Avionics & Pre-flight Maintenance', 'COMPLETED', 47, 48) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (94, 'Cabin Cleaning & Decontamination', 'BLOCKED', 47, 3) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (95, 'Aviation Refueling & Density Check', 'PENDING', 48, 49) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (96, 'Catering & Galley Supply Loading', 'IN_PROGRESS', 48, 4) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (97, 'Baggage & Freight Loading', 'COMPLETED', 49, 50) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (98, 'Avionics & Pre-flight Maintenance', 'BLOCKED', 49, 5) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (99, 'Cabin Cleaning & Decontamination', 'PENDING', 50, 1) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (100, 'Aviation Refueling & Density Check', 'IN_PROGRESS', 50, 6) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (101, 'Catering & Galley Supply Loading', 'COMPLETED', 51, 2) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (102, 'Baggage & Freight Loading', 'BLOCKED', 51, 7) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (103, 'Avionics & Pre-flight Maintenance', 'PENDING', 52, 3) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (104, 'Cabin Cleaning & Decontamination', 'IN_PROGRESS', 52, 8) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (105, 'Aviation Refueling & Density Check', 'COMPLETED', 53, 4) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (106, 'Catering & Galley Supply Loading', 'BLOCKED', 53, 9) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (107, 'Baggage & Freight Loading', 'PENDING', 54, 5) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (108, 'Avionics & Pre-flight Maintenance', 'IN_PROGRESS', 54, 10) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (109, 'Cabin Cleaning & Decontamination', 'COMPLETED', 55, 6) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (110, 'Aviation Refueling & Density Check', 'BLOCKED', 55, 11) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (111, 'Catering & Galley Supply Loading', 'PENDING', 56, 7) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (112, 'Baggage & Freight Loading', 'IN_PROGRESS', 56, 12) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (113, 'Avionics & Pre-flight Maintenance', 'COMPLETED', 57, 8) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (114, 'Cabin Cleaning & Decontamination', 'BLOCKED', 57, 13) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (115, 'Aviation Refueling & Density Check', 'PENDING', 58, 9) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (116, 'Catering & Galley Supply Loading', 'IN_PROGRESS', 58, 14) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (117, 'Baggage & Freight Loading', 'COMPLETED', 59, 10) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (118, 'Avionics & Pre-flight Maintenance', 'BLOCKED', 59, 15) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (119, 'Cabin Cleaning & Decontamination', 'PENDING', 60, 11) ON CONFLICT DO NOTHING;
INSERT INTO tasks (task_id, task_name, status, flight_id, assigned_user_id) VALUES (120, 'Aviation Refueling & Density Check', 'IN_PROGRESS', 60, 16) ON CONFLICT DO NOTHING;

-- 10. DELAY_LOGS (35)
INSERT INTO delay_logs (flight_id, delay_seq_no, delay_minutes) VALUES (1, 1, 22) ON CONFLICT DO NOTHING;
INSERT INTO delay_logs (flight_id, delay_seq_no, delay_minutes) VALUES (2, 1, 34) ON CONFLICT DO NOTHING;
INSERT INTO delay_logs (flight_id, delay_seq_no, delay_minutes) VALUES (3, 1, 46) ON CONFLICT DO NOTHING;
INSERT INTO delay_logs (flight_id, delay_seq_no, delay_minutes) VALUES (4, 1, 58) ON CONFLICT DO NOTHING;
INSERT INTO delay_logs (flight_id, delay_seq_no, delay_minutes) VALUES (5, 1, 70) ON CONFLICT DO NOTHING;
INSERT INTO delay_logs (flight_id, delay_seq_no, delay_minutes) VALUES (6, 1, 82) ON CONFLICT DO NOTHING;
INSERT INTO delay_logs (flight_id, delay_seq_no, delay_minutes) VALUES (7, 1, 94) ON CONFLICT DO NOTHING;
INSERT INTO delay_logs (flight_id, delay_seq_no, delay_minutes) VALUES (8, 1, 11) ON CONFLICT DO NOTHING;
INSERT INTO delay_logs (flight_id, delay_seq_no, delay_minutes) VALUES (9, 1, 23) ON CONFLICT DO NOTHING;
INSERT INTO delay_logs (flight_id, delay_seq_no, delay_minutes) VALUES (10, 1, 35) ON CONFLICT DO NOTHING;
INSERT INTO delay_logs (flight_id, delay_seq_no, delay_minutes) VALUES (11, 1, 47) ON CONFLICT DO NOTHING;
INSERT INTO delay_logs (flight_id, delay_seq_no, delay_minutes) VALUES (12, 1, 59) ON CONFLICT DO NOTHING;
INSERT INTO delay_logs (flight_id, delay_seq_no, delay_minutes) VALUES (13, 1, 71) ON CONFLICT DO NOTHING;
INSERT INTO delay_logs (flight_id, delay_seq_no, delay_minutes) VALUES (14, 1, 83) ON CONFLICT DO NOTHING;
INSERT INTO delay_logs (flight_id, delay_seq_no, delay_minutes) VALUES (15, 1, 95) ON CONFLICT DO NOTHING;
INSERT INTO delay_logs (flight_id, delay_seq_no, delay_minutes) VALUES (16, 1, 12) ON CONFLICT DO NOTHING;
INSERT INTO delay_logs (flight_id, delay_seq_no, delay_minutes) VALUES (17, 1, 24) ON CONFLICT DO NOTHING;
INSERT INTO delay_logs (flight_id, delay_seq_no, delay_minutes) VALUES (18, 1, 36) ON CONFLICT DO NOTHING;
INSERT INTO delay_logs (flight_id, delay_seq_no, delay_minutes) VALUES (19, 1, 48) ON CONFLICT DO NOTHING;
INSERT INTO delay_logs (flight_id, delay_seq_no, delay_minutes) VALUES (20, 1, 60) ON CONFLICT DO NOTHING;
INSERT INTO delay_logs (flight_id, delay_seq_no, delay_minutes) VALUES (21, 1, 72) ON CONFLICT DO NOTHING;
INSERT INTO delay_logs (flight_id, delay_seq_no, delay_minutes) VALUES (22, 1, 84) ON CONFLICT DO NOTHING;
INSERT INTO delay_logs (flight_id, delay_seq_no, delay_minutes) VALUES (23, 1, 96) ON CONFLICT DO NOTHING;
INSERT INTO delay_logs (flight_id, delay_seq_no, delay_minutes) VALUES (24, 1, 13) ON CONFLICT DO NOTHING;
INSERT INTO delay_logs (flight_id, delay_seq_no, delay_minutes) VALUES (25, 1, 25) ON CONFLICT DO NOTHING;
INSERT INTO delay_logs (flight_id, delay_seq_no, delay_minutes) VALUES (26, 1, 37) ON CONFLICT DO NOTHING;
INSERT INTO delay_logs (flight_id, delay_seq_no, delay_minutes) VALUES (27, 1, 49) ON CONFLICT DO NOTHING;
INSERT INTO delay_logs (flight_id, delay_seq_no, delay_minutes) VALUES (28, 1, 61) ON CONFLICT DO NOTHING;
INSERT INTO delay_logs (flight_id, delay_seq_no, delay_minutes) VALUES (29, 1, 73) ON CONFLICT DO NOTHING;
INSERT INTO delay_logs (flight_id, delay_seq_no, delay_minutes) VALUES (30, 1, 85) ON CONFLICT DO NOTHING;
INSERT INTO delay_logs (flight_id, delay_seq_no, delay_minutes) VALUES (31, 1, 97) ON CONFLICT DO NOTHING;
INSERT INTO delay_logs (flight_id, delay_seq_no, delay_minutes) VALUES (32, 1, 14) ON CONFLICT DO NOTHING;
INSERT INTO delay_logs (flight_id, delay_seq_no, delay_minutes) VALUES (33, 1, 26) ON CONFLICT DO NOTHING;
INSERT INTO delay_logs (flight_id, delay_seq_no, delay_minutes) VALUES (34, 1, 38) ON CONFLICT DO NOTHING;
INSERT INTO delay_logs (flight_id, delay_seq_no, delay_minutes) VALUES (35, 1, 50) ON CONFLICT DO NOTHING;

-- 11. FUEL_LOGS (40)
INSERT INTO fuel_logs (fuel_log_id, fuel_density, task_id) VALUES (1, 0.801, 2) ON CONFLICT DO NOTHING;
INSERT INTO fuel_logs (fuel_log_id, fuel_density, task_id) VALUES (2, 0.802, 4) ON CONFLICT DO NOTHING;
INSERT INTO fuel_logs (fuel_log_id, fuel_density, task_id) VALUES (3, 0.803, 6) ON CONFLICT DO NOTHING;
INSERT INTO fuel_logs (fuel_log_id, fuel_density, task_id) VALUES (4, 0.804, 8) ON CONFLICT DO NOTHING;
INSERT INTO fuel_logs (fuel_log_id, fuel_density, task_id) VALUES (5, 0.805, 10) ON CONFLICT DO NOTHING;
INSERT INTO fuel_logs (fuel_log_id, fuel_density, task_id) VALUES (6, 0.806, 12) ON CONFLICT DO NOTHING;
INSERT INTO fuel_logs (fuel_log_id, fuel_density, task_id) VALUES (7, 0.807, 14) ON CONFLICT DO NOTHING;
INSERT INTO fuel_logs (fuel_log_id, fuel_density, task_id) VALUES (8, 0.808, 16) ON CONFLICT DO NOTHING;
INSERT INTO fuel_logs (fuel_log_id, fuel_density, task_id) VALUES (9, 0.809, 18) ON CONFLICT DO NOTHING;
INSERT INTO fuel_logs (fuel_log_id, fuel_density, task_id) VALUES (10, 0.800, 20) ON CONFLICT DO NOTHING;
INSERT INTO fuel_logs (fuel_log_id, fuel_density, task_id) VALUES (11, 0.801, 22) ON CONFLICT DO NOTHING;
INSERT INTO fuel_logs (fuel_log_id, fuel_density, task_id) VALUES (12, 0.802, 24) ON CONFLICT DO NOTHING;
INSERT INTO fuel_logs (fuel_log_id, fuel_density, task_id) VALUES (13, 0.803, 26) ON CONFLICT DO NOTHING;
INSERT INTO fuel_logs (fuel_log_id, fuel_density, task_id) VALUES (14, 0.804, 28) ON CONFLICT DO NOTHING;
INSERT INTO fuel_logs (fuel_log_id, fuel_density, task_id) VALUES (15, 0.805, 30) ON CONFLICT DO NOTHING;
INSERT INTO fuel_logs (fuel_log_id, fuel_density, task_id) VALUES (16, 0.806, 32) ON CONFLICT DO NOTHING;
INSERT INTO fuel_logs (fuel_log_id, fuel_density, task_id) VALUES (17, 0.807, 34) ON CONFLICT DO NOTHING;
INSERT INTO fuel_logs (fuel_log_id, fuel_density, task_id) VALUES (18, 0.808, 36) ON CONFLICT DO NOTHING;
INSERT INTO fuel_logs (fuel_log_id, fuel_density, task_id) VALUES (19, 0.809, 38) ON CONFLICT DO NOTHING;
INSERT INTO fuel_logs (fuel_log_id, fuel_density, task_id) VALUES (20, 0.800, 40) ON CONFLICT DO NOTHING;
INSERT INTO fuel_logs (fuel_log_id, fuel_density, task_id) VALUES (21, 0.801, 42) ON CONFLICT DO NOTHING;
INSERT INTO fuel_logs (fuel_log_id, fuel_density, task_id) VALUES (22, 0.802, 44) ON CONFLICT DO NOTHING;
INSERT INTO fuel_logs (fuel_log_id, fuel_density, task_id) VALUES (23, 0.803, 46) ON CONFLICT DO NOTHING;
INSERT INTO fuel_logs (fuel_log_id, fuel_density, task_id) VALUES (24, 0.804, 48) ON CONFLICT DO NOTHING;
INSERT INTO fuel_logs (fuel_log_id, fuel_density, task_id) VALUES (25, 0.805, 50) ON CONFLICT DO NOTHING;
INSERT INTO fuel_logs (fuel_log_id, fuel_density, task_id) VALUES (26, 0.806, 52) ON CONFLICT DO NOTHING;
INSERT INTO fuel_logs (fuel_log_id, fuel_density, task_id) VALUES (27, 0.807, 54) ON CONFLICT DO NOTHING;
INSERT INTO fuel_logs (fuel_log_id, fuel_density, task_id) VALUES (28, 0.808, 56) ON CONFLICT DO NOTHING;
INSERT INTO fuel_logs (fuel_log_id, fuel_density, task_id) VALUES (29, 0.809, 58) ON CONFLICT DO NOTHING;
INSERT INTO fuel_logs (fuel_log_id, fuel_density, task_id) VALUES (30, 0.800, 60) ON CONFLICT DO NOTHING;
INSERT INTO fuel_logs (fuel_log_id, fuel_density, task_id) VALUES (31, 0.801, 62) ON CONFLICT DO NOTHING;
INSERT INTO fuel_logs (fuel_log_id, fuel_density, task_id) VALUES (32, 0.802, 64) ON CONFLICT DO NOTHING;
INSERT INTO fuel_logs (fuel_log_id, fuel_density, task_id) VALUES (33, 0.803, 66) ON CONFLICT DO NOTHING;
INSERT INTO fuel_logs (fuel_log_id, fuel_density, task_id) VALUES (34, 0.804, 68) ON CONFLICT DO NOTHING;
INSERT INTO fuel_logs (fuel_log_id, fuel_density, task_id) VALUES (35, 0.805, 70) ON CONFLICT DO NOTHING;
INSERT INTO fuel_logs (fuel_log_id, fuel_density, task_id) VALUES (36, 0.806, 72) ON CONFLICT DO NOTHING;
INSERT INTO fuel_logs (fuel_log_id, fuel_density, task_id) VALUES (37, 0.807, 74) ON CONFLICT DO NOTHING;
INSERT INTO fuel_logs (fuel_log_id, fuel_density, task_id) VALUES (38, 0.808, 76) ON CONFLICT DO NOTHING;
INSERT INTO fuel_logs (fuel_log_id, fuel_density, task_id) VALUES (39, 0.809, 78) ON CONFLICT DO NOTHING;
INSERT INTO fuel_logs (fuel_log_id, fuel_density, task_id) VALUES (40, 0.800, 80) ON CONFLICT DO NOTHING;

-- 12. CARGO_MANIFESTS (40)
INSERT INTO cargo_manifests (cargo_id, container_id, fuel_log_id) VALUES (1, 'AKN-01001-AOCS', 1) ON CONFLICT DO NOTHING;
INSERT INTO cargo_manifests (cargo_id, container_id, fuel_log_id) VALUES (2, 'AKN-01002-AOCS', 2) ON CONFLICT DO NOTHING;
INSERT INTO cargo_manifests (cargo_id, container_id, fuel_log_id) VALUES (3, 'AKN-01003-AOCS', 3) ON CONFLICT DO NOTHING;
INSERT INTO cargo_manifests (cargo_id, container_id, fuel_log_id) VALUES (4, 'AKN-01004-AOCS', 4) ON CONFLICT DO NOTHING;
INSERT INTO cargo_manifests (cargo_id, container_id, fuel_log_id) VALUES (5, 'AKN-01005-AOCS', 5) ON CONFLICT DO NOTHING;
INSERT INTO cargo_manifests (cargo_id, container_id, fuel_log_id) VALUES (6, 'AKN-01006-AOCS', 6) ON CONFLICT DO NOTHING;
INSERT INTO cargo_manifests (cargo_id, container_id, fuel_log_id) VALUES (7, 'AKN-01007-AOCS', 7) ON CONFLICT DO NOTHING;
INSERT INTO cargo_manifests (cargo_id, container_id, fuel_log_id) VALUES (8, 'AKN-01008-AOCS', 8) ON CONFLICT DO NOTHING;
INSERT INTO cargo_manifests (cargo_id, container_id, fuel_log_id) VALUES (9, 'AKN-01009-AOCS', 9) ON CONFLICT DO NOTHING;
INSERT INTO cargo_manifests (cargo_id, container_id, fuel_log_id) VALUES (10, 'AKN-01010-AOCS', 10) ON CONFLICT DO NOTHING;
INSERT INTO cargo_manifests (cargo_id, container_id, fuel_log_id) VALUES (11, 'AKN-01011-AOCS', 11) ON CONFLICT DO NOTHING;
INSERT INTO cargo_manifests (cargo_id, container_id, fuel_log_id) VALUES (12, 'AKN-01012-AOCS', 12) ON CONFLICT DO NOTHING;
INSERT INTO cargo_manifests (cargo_id, container_id, fuel_log_id) VALUES (13, 'AKN-01013-AOCS', 13) ON CONFLICT DO NOTHING;
INSERT INTO cargo_manifests (cargo_id, container_id, fuel_log_id) VALUES (14, 'AKN-01014-AOCS', 14) ON CONFLICT DO NOTHING;
INSERT INTO cargo_manifests (cargo_id, container_id, fuel_log_id) VALUES (15, 'AKN-01015-AOCS', 15) ON CONFLICT DO NOTHING;
INSERT INTO cargo_manifests (cargo_id, container_id, fuel_log_id) VALUES (16, 'AKN-01016-AOCS', 16) ON CONFLICT DO NOTHING;
INSERT INTO cargo_manifests (cargo_id, container_id, fuel_log_id) VALUES (17, 'AKN-01017-AOCS', 17) ON CONFLICT DO NOTHING;
INSERT INTO cargo_manifests (cargo_id, container_id, fuel_log_id) VALUES (18, 'AKN-01018-AOCS', 18) ON CONFLICT DO NOTHING;
INSERT INTO cargo_manifests (cargo_id, container_id, fuel_log_id) VALUES (19, 'AKN-01019-AOCS', 19) ON CONFLICT DO NOTHING;
INSERT INTO cargo_manifests (cargo_id, container_id, fuel_log_id) VALUES (20, 'AKN-01020-AOCS', 20) ON CONFLICT DO NOTHING;
INSERT INTO cargo_manifests (cargo_id, container_id, fuel_log_id) VALUES (21, 'AKN-01021-AOCS', 21) ON CONFLICT DO NOTHING;
INSERT INTO cargo_manifests (cargo_id, container_id, fuel_log_id) VALUES (22, 'AKN-01022-AOCS', 22) ON CONFLICT DO NOTHING;
INSERT INTO cargo_manifests (cargo_id, container_id, fuel_log_id) VALUES (23, 'AKN-01023-AOCS', 23) ON CONFLICT DO NOTHING;
INSERT INTO cargo_manifests (cargo_id, container_id, fuel_log_id) VALUES (24, 'AKN-01024-AOCS', 24) ON CONFLICT DO NOTHING;
INSERT INTO cargo_manifests (cargo_id, container_id, fuel_log_id) VALUES (25, 'AKN-01025-AOCS', 25) ON CONFLICT DO NOTHING;
INSERT INTO cargo_manifests (cargo_id, container_id, fuel_log_id) VALUES (26, 'AKN-01026-AOCS', 26) ON CONFLICT DO NOTHING;
INSERT INTO cargo_manifests (cargo_id, container_id, fuel_log_id) VALUES (27, 'AKN-01027-AOCS', 27) ON CONFLICT DO NOTHING;
INSERT INTO cargo_manifests (cargo_id, container_id, fuel_log_id) VALUES (28, 'AKN-01028-AOCS', 28) ON CONFLICT DO NOTHING;
INSERT INTO cargo_manifests (cargo_id, container_id, fuel_log_id) VALUES (29, 'AKN-01029-AOCS', 29) ON CONFLICT DO NOTHING;
INSERT INTO cargo_manifests (cargo_id, container_id, fuel_log_id) VALUES (30, 'AKN-01030-AOCS', 30) ON CONFLICT DO NOTHING;
INSERT INTO cargo_manifests (cargo_id, container_id, fuel_log_id) VALUES (31, 'AKN-01031-AOCS', 31) ON CONFLICT DO NOTHING;
INSERT INTO cargo_manifests (cargo_id, container_id, fuel_log_id) VALUES (32, 'AKN-01032-AOCS', 32) ON CONFLICT DO NOTHING;
INSERT INTO cargo_manifests (cargo_id, container_id, fuel_log_id) VALUES (33, 'AKN-01033-AOCS', 33) ON CONFLICT DO NOTHING;
INSERT INTO cargo_manifests (cargo_id, container_id, fuel_log_id) VALUES (34, 'AKN-01034-AOCS', 34) ON CONFLICT DO NOTHING;
INSERT INTO cargo_manifests (cargo_id, container_id, fuel_log_id) VALUES (35, 'AKN-01035-AOCS', 35) ON CONFLICT DO NOTHING;
INSERT INTO cargo_manifests (cargo_id, container_id, fuel_log_id) VALUES (36, 'AKN-01036-AOCS', 36) ON CONFLICT DO NOTHING;
INSERT INTO cargo_manifests (cargo_id, container_id, fuel_log_id) VALUES (37, 'AKN-01037-AOCS', 37) ON CONFLICT DO NOTHING;
INSERT INTO cargo_manifests (cargo_id, container_id, fuel_log_id) VALUES (38, 'AKN-01038-AOCS', 38) ON CONFLICT DO NOTHING;
INSERT INTO cargo_manifests (cargo_id, container_id, fuel_log_id) VALUES (39, 'AKN-01039-AOCS', 39) ON CONFLICT DO NOTHING;
INSERT INTO cargo_manifests (cargo_id, container_id, fuel_log_id) VALUES (40, 'AKN-01040-AOCS', 40) ON CONFLICT DO NOTHING;

-- 13. BAGGAGE_CAROUSELS (15)
INSERT INTO baggage_carousels (carousel_id, terminal, flight_id) VALUES (1, 'T1', 4) ON CONFLICT DO NOTHING;
INSERT INTO baggage_carousels (carousel_id, terminal, flight_id) VALUES (2, 'T1', 8) ON CONFLICT DO NOTHING;
INSERT INTO baggage_carousels (carousel_id, terminal, flight_id) VALUES (3, 'T1', 12) ON CONFLICT DO NOTHING;
INSERT INTO baggage_carousels (carousel_id, terminal, flight_id) VALUES (4, 'T1', 16) ON CONFLICT DO NOTHING;
INSERT INTO baggage_carousels (carousel_id, terminal, flight_id) VALUES (5, 'T1', 20) ON CONFLICT DO NOTHING;
INSERT INTO baggage_carousels (carousel_id, terminal, flight_id) VALUES (6, 'T2', 24) ON CONFLICT DO NOTHING;
INSERT INTO baggage_carousels (carousel_id, terminal, flight_id) VALUES (7, 'T2', 28) ON CONFLICT DO NOTHING;
INSERT INTO baggage_carousels (carousel_id, terminal, flight_id) VALUES (8, 'T2', 32) ON CONFLICT DO NOTHING;
INSERT INTO baggage_carousels (carousel_id, terminal, flight_id) VALUES (9, 'T2', 36) ON CONFLICT DO NOTHING;
INSERT INTO baggage_carousels (carousel_id, terminal, flight_id) VALUES (10, 'T2', 40) ON CONFLICT DO NOTHING;
INSERT INTO baggage_carousels (carousel_id, terminal, flight_id) VALUES (11, 'T3', 44) ON CONFLICT DO NOTHING;
INSERT INTO baggage_carousels (carousel_id, terminal, flight_id) VALUES (12, 'T3', 48) ON CONFLICT DO NOTHING;
INSERT INTO baggage_carousels (carousel_id, terminal, flight_id) VALUES (13, 'T3', 52) ON CONFLICT DO NOTHING;
INSERT INTO baggage_carousels (carousel_id, terminal, flight_id) VALUES (14, 'T3', 56) ON CONFLICT DO NOTHING;
INSERT INTO baggage_carousels (carousel_id, terminal, flight_id) VALUES (15, 'T3', 60) ON CONFLICT DO NOTHING;

-- 14. PASSENGERS (60)
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (1, 'P01000777', 2) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (2, 'P01001554', 3) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (3, 'P01002331', 4) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (4, 'P01003108', 5) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (5, 'P01003885', 6) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (6, 'P01004662', 7) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (7, 'P01005439', 8) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (8, 'P01006216', 9) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (9, 'P01006993', 10) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (10, 'P01007770', 11) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (11, 'P01008547', 12) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (12, 'P01009324', 13) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (13, 'P01010101', 14) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (14, 'P01010878', 15) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (15, 'P01011655', 16) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (16, 'P01012432', 17) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (17, 'P01013209', 18) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (18, 'P01013986', 19) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (19, 'P01014763', 20) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (20, 'P01015540', 21) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (21, 'P01016317', 22) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (22, 'P01017094', 23) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (23, 'P01017871', 24) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (24, 'P01018648', 25) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (25, 'P01019425', 26) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (26, 'P01020202', 27) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (27, 'P01020979', 28) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (28, 'P01021756', 29) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (29, 'P01022533', 30) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (30, 'P01023310', 31) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (31, 'P01024087', 32) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (32, 'P01024864', 33) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (33, 'P01025641', 34) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (34, 'P01026418', 35) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (35, 'P01027195', 36) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (36, 'P01027972', 37) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (37, 'P01028749', 38) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (38, 'P01029526', 39) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (39, 'P01030303', 40) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (40, 'P01031080', 41) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (41, 'P01031857', 42) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (42, 'P01032634', 43) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (43, 'P01033411', 44) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (44, 'P01034188', 45) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (45, 'P01034965', 46) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (46, 'P01035742', 47) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (47, 'P01036519', 48) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (48, 'P01037296', 49) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (49, 'P01038073', 50) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (50, 'P01038850', 51) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (51, 'P01039627', 52) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (52, 'P01040404', 53) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (53, 'P01041181', 54) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (54, 'P01041958', 55) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (55, 'P01042735', 56) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (56, 'P01043512', 57) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (57, 'P01044289', 58) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (58, 'P01045066', 59) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (59, 'P01045843', 60) ON CONFLICT DO NOTHING;
INSERT INTO passengers (passenger_id, passport_number, flight_id) VALUES (60, 'P01046620', 1) ON CONFLICT DO NOTHING;

-- 15. LOUNGE_VISITS (30)
INSERT INTO lounge_visits (visit_id, lounge_name, passenger_id) VALUES (1, 'Encalm VIP Executive Lounge', 2) ON CONFLICT DO NOTHING;
INSERT INTO lounge_visits (visit_id, lounge_name, passenger_id) VALUES (2, 'Emirates First Class Lounge', 4) ON CONFLICT DO NOTHING;
INSERT INTO lounge_visits (visit_id, lounge_name, passenger_id) VALUES (3, 'Star Alliance Lounge', 6) ON CONFLICT DO NOTHING;
INSERT INTO lounge_visits (visit_id, lounge_name, passenger_id) VALUES (4, 'Plaza Premium Executive Lounge', 8) ON CONFLICT DO NOTHING;
INSERT INTO lounge_visits (visit_id, lounge_name, passenger_id) VALUES (5, 'Encalm VIP Executive Lounge', 10) ON CONFLICT DO NOTHING;
INSERT INTO lounge_visits (visit_id, lounge_name, passenger_id) VALUES (6, 'Emirates First Class Lounge', 12) ON CONFLICT DO NOTHING;
INSERT INTO lounge_visits (visit_id, lounge_name, passenger_id) VALUES (7, 'Star Alliance Lounge', 14) ON CONFLICT DO NOTHING;
INSERT INTO lounge_visits (visit_id, lounge_name, passenger_id) VALUES (8, 'Plaza Premium Executive Lounge', 16) ON CONFLICT DO NOTHING;
INSERT INTO lounge_visits (visit_id, lounge_name, passenger_id) VALUES (9, 'Encalm VIP Executive Lounge', 18) ON CONFLICT DO NOTHING;
INSERT INTO lounge_visits (visit_id, lounge_name, passenger_id) VALUES (10, 'Emirates First Class Lounge', 20) ON CONFLICT DO NOTHING;
INSERT INTO lounge_visits (visit_id, lounge_name, passenger_id) VALUES (11, 'Star Alliance Lounge', 22) ON CONFLICT DO NOTHING;
INSERT INTO lounge_visits (visit_id, lounge_name, passenger_id) VALUES (12, 'Plaza Premium Executive Lounge', 24) ON CONFLICT DO NOTHING;
INSERT INTO lounge_visits (visit_id, lounge_name, passenger_id) VALUES (13, 'Encalm VIP Executive Lounge', 26) ON CONFLICT DO NOTHING;
INSERT INTO lounge_visits (visit_id, lounge_name, passenger_id) VALUES (14, 'Emirates First Class Lounge', 28) ON CONFLICT DO NOTHING;
INSERT INTO lounge_visits (visit_id, lounge_name, passenger_id) VALUES (15, 'Star Alliance Lounge', 30) ON CONFLICT DO NOTHING;
INSERT INTO lounge_visits (visit_id, lounge_name, passenger_id) VALUES (16, 'Plaza Premium Executive Lounge', 32) ON CONFLICT DO NOTHING;
INSERT INTO lounge_visits (visit_id, lounge_name, passenger_id) VALUES (17, 'Encalm VIP Executive Lounge', 34) ON CONFLICT DO NOTHING;
INSERT INTO lounge_visits (visit_id, lounge_name, passenger_id) VALUES (18, 'Emirates First Class Lounge', 36) ON CONFLICT DO NOTHING;
INSERT INTO lounge_visits (visit_id, lounge_name, passenger_id) VALUES (19, 'Star Alliance Lounge', 38) ON CONFLICT DO NOTHING;
INSERT INTO lounge_visits (visit_id, lounge_name, passenger_id) VALUES (20, 'Plaza Premium Executive Lounge', 40) ON CONFLICT DO NOTHING;
INSERT INTO lounge_visits (visit_id, lounge_name, passenger_id) VALUES (21, 'Encalm VIP Executive Lounge', 42) ON CONFLICT DO NOTHING;
INSERT INTO lounge_visits (visit_id, lounge_name, passenger_id) VALUES (22, 'Emirates First Class Lounge', 44) ON CONFLICT DO NOTHING;
INSERT INTO lounge_visits (visit_id, lounge_name, passenger_id) VALUES (23, 'Star Alliance Lounge', 46) ON CONFLICT DO NOTHING;
INSERT INTO lounge_visits (visit_id, lounge_name, passenger_id) VALUES (24, 'Plaza Premium Executive Lounge', 48) ON CONFLICT DO NOTHING;
INSERT INTO lounge_visits (visit_id, lounge_name, passenger_id) VALUES (25, 'Encalm VIP Executive Lounge', 50) ON CONFLICT DO NOTHING;
INSERT INTO lounge_visits (visit_id, lounge_name, passenger_id) VALUES (26, 'Emirates First Class Lounge', 52) ON CONFLICT DO NOTHING;
INSERT INTO lounge_visits (visit_id, lounge_name, passenger_id) VALUES (27, 'Star Alliance Lounge', 54) ON CONFLICT DO NOTHING;
INSERT INTO lounge_visits (visit_id, lounge_name, passenger_id) VALUES (28, 'Plaza Premium Executive Lounge', 56) ON CONFLICT DO NOTHING;
INSERT INTO lounge_visits (visit_id, lounge_name, passenger_id) VALUES (29, 'Encalm VIP Executive Lounge', 58) ON CONFLICT DO NOTHING;
INSERT INTO lounge_visits (visit_id, lounge_name, passenger_id) VALUES (30, 'Emirates First Class Lounge', 60) ON CONFLICT DO NOTHING;

-- 16. NOTIFICATIONS (40)
INSERT INTO notifications (notification_id, title, user_id) VALUES (1, 'Gate Change Alert: Reassigned to Gate A12', 2) ON CONFLICT DO NOTHING;
INSERT INTO notifications (notification_id, title, user_id) VALUES (2, 'Turnaround SLA Alert: Refueling Delay Detected', 3) ON CONFLICT DO NOTHING;
INSERT INTO notifications (notification_id, title, user_id) VALUES (3, 'Airside Clearance: Runway 28L Ready for Arrival', 4) ON CONFLICT DO NOTHING;
INSERT INTO notifications (notification_id, title, user_id) VALUES (4, 'Security Clearance: Baggage Carousel 4 Active', 5) ON CONFLICT DO NOTHING;
INSERT INTO notifications (notification_id, title, user_id) VALUES (5, 'Flight Dispatch: Flight Schedule Updated', 6) ON CONFLICT DO NOTHING;
INSERT INTO notifications (notification_id, title, user_id) VALUES (6, 'Gate Change Alert: Reassigned to Gate A12', 7) ON CONFLICT DO NOTHING;
INSERT INTO notifications (notification_id, title, user_id) VALUES (7, 'Turnaround SLA Alert: Refueling Delay Detected', 8) ON CONFLICT DO NOTHING;
INSERT INTO notifications (notification_id, title, user_id) VALUES (8, 'Airside Clearance: Runway 28L Ready for Arrival', 9) ON CONFLICT DO NOTHING;
INSERT INTO notifications (notification_id, title, user_id) VALUES (9, 'Security Clearance: Baggage Carousel 4 Active', 10) ON CONFLICT DO NOTHING;
INSERT INTO notifications (notification_id, title, user_id) VALUES (10, 'Flight Dispatch: Flight Schedule Updated', 11) ON CONFLICT DO NOTHING;
INSERT INTO notifications (notification_id, title, user_id) VALUES (11, 'Gate Change Alert: Reassigned to Gate A12', 12) ON CONFLICT DO NOTHING;
INSERT INTO notifications (notification_id, title, user_id) VALUES (12, 'Turnaround SLA Alert: Refueling Delay Detected', 13) ON CONFLICT DO NOTHING;
INSERT INTO notifications (notification_id, title, user_id) VALUES (13, 'Airside Clearance: Runway 28L Ready for Arrival', 14) ON CONFLICT DO NOTHING;
INSERT INTO notifications (notification_id, title, user_id) VALUES (14, 'Security Clearance: Baggage Carousel 4 Active', 15) ON CONFLICT DO NOTHING;
INSERT INTO notifications (notification_id, title, user_id) VALUES (15, 'Flight Dispatch: Flight Schedule Updated', 16) ON CONFLICT DO NOTHING;
INSERT INTO notifications (notification_id, title, user_id) VALUES (16, 'Gate Change Alert: Reassigned to Gate A12', 17) ON CONFLICT DO NOTHING;
INSERT INTO notifications (notification_id, title, user_id) VALUES (17, 'Turnaround SLA Alert: Refueling Delay Detected', 18) ON CONFLICT DO NOTHING;
INSERT INTO notifications (notification_id, title, user_id) VALUES (18, 'Airside Clearance: Runway 28L Ready for Arrival', 19) ON CONFLICT DO NOTHING;
INSERT INTO notifications (notification_id, title, user_id) VALUES (19, 'Security Clearance: Baggage Carousel 4 Active', 20) ON CONFLICT DO NOTHING;
INSERT INTO notifications (notification_id, title, user_id) VALUES (20, 'Flight Dispatch: Flight Schedule Updated', 21) ON CONFLICT DO NOTHING;
INSERT INTO notifications (notification_id, title, user_id) VALUES (21, 'Gate Change Alert: Reassigned to Gate A12', 22) ON CONFLICT DO NOTHING;
INSERT INTO notifications (notification_id, title, user_id) VALUES (22, 'Turnaround SLA Alert: Refueling Delay Detected', 23) ON CONFLICT DO NOTHING;
INSERT INTO notifications (notification_id, title, user_id) VALUES (23, 'Airside Clearance: Runway 28L Ready for Arrival', 24) ON CONFLICT DO NOTHING;
INSERT INTO notifications (notification_id, title, user_id) VALUES (24, 'Security Clearance: Baggage Carousel 4 Active', 25) ON CONFLICT DO NOTHING;
INSERT INTO notifications (notification_id, title, user_id) VALUES (25, 'Flight Dispatch: Flight Schedule Updated', 26) ON CONFLICT DO NOTHING;
INSERT INTO notifications (notification_id, title, user_id) VALUES (26, 'Gate Change Alert: Reassigned to Gate A12', 27) ON CONFLICT DO NOTHING;
INSERT INTO notifications (notification_id, title, user_id) VALUES (27, 'Turnaround SLA Alert: Refueling Delay Detected', 28) ON CONFLICT DO NOTHING;
INSERT INTO notifications (notification_id, title, user_id) VALUES (28, 'Airside Clearance: Runway 28L Ready for Arrival', 29) ON CONFLICT DO NOTHING;
INSERT INTO notifications (notification_id, title, user_id) VALUES (29, 'Security Clearance: Baggage Carousel 4 Active', 30) ON CONFLICT DO NOTHING;
INSERT INTO notifications (notification_id, title, user_id) VALUES (30, 'Flight Dispatch: Flight Schedule Updated', 31) ON CONFLICT DO NOTHING;
INSERT INTO notifications (notification_id, title, user_id) VALUES (31, 'Gate Change Alert: Reassigned to Gate A12', 32) ON CONFLICT DO NOTHING;
INSERT INTO notifications (notification_id, title, user_id) VALUES (32, 'Turnaround SLA Alert: Refueling Delay Detected', 33) ON CONFLICT DO NOTHING;
INSERT INTO notifications (notification_id, title, user_id) VALUES (33, 'Airside Clearance: Runway 28L Ready for Arrival', 34) ON CONFLICT DO NOTHING;
INSERT INTO notifications (notification_id, title, user_id) VALUES (34, 'Security Clearance: Baggage Carousel 4 Active', 35) ON CONFLICT DO NOTHING;
INSERT INTO notifications (notification_id, title, user_id) VALUES (35, 'Flight Dispatch: Flight Schedule Updated', 36) ON CONFLICT DO NOTHING;
INSERT INTO notifications (notification_id, title, user_id) VALUES (36, 'Gate Change Alert: Reassigned to Gate A12', 37) ON CONFLICT DO NOTHING;
INSERT INTO notifications (notification_id, title, user_id) VALUES (37, 'Turnaround SLA Alert: Refueling Delay Detected', 38) ON CONFLICT DO NOTHING;
INSERT INTO notifications (notification_id, title, user_id) VALUES (38, 'Airside Clearance: Runway 28L Ready for Arrival', 39) ON CONFLICT DO NOTHING;
INSERT INTO notifications (notification_id, title, user_id) VALUES (39, 'Security Clearance: Baggage Carousel 4 Active', 40) ON CONFLICT DO NOTHING;
INSERT INTO notifications (notification_id, title, user_id) VALUES (40, 'Flight Dispatch: Flight Schedule Updated', 41) ON CONFLICT DO NOTHING;

-- 17. AUDIT_LOGS (50)
INSERT INTO audit_logs (log_id, action, user_id) VALUES (1, 'User Login Succeeded', 2) ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (log_id, action, user_id) VALUES (2, 'Gate Assignment Modified', 3) ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (log_id, action, user_id) VALUES (3, 'Flight Status Updated to BOARDING', 4) ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (log_id, action, user_id) VALUES (4, 'Refueling Density Transaction Completed', 5) ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (log_id, action, user_id) VALUES (5, 'Ground Turnaround Sub-Task Closed', 6) ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (log_id, action, user_id) VALUES (6, 'User Login Succeeded', 7) ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (log_id, action, user_id) VALUES (7, 'Gate Assignment Modified', 8) ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (log_id, action, user_id) VALUES (8, 'Flight Status Updated to BOARDING', 9) ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (log_id, action, user_id) VALUES (9, 'Refueling Density Transaction Completed', 10) ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (log_id, action, user_id) VALUES (10, 'Ground Turnaround Sub-Task Closed', 11) ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (log_id, action, user_id) VALUES (11, 'User Login Succeeded', 12) ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (log_id, action, user_id) VALUES (12, 'Gate Assignment Modified', 13) ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (log_id, action, user_id) VALUES (13, 'Flight Status Updated to BOARDING', 14) ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (log_id, action, user_id) VALUES (14, 'Refueling Density Transaction Completed', 15) ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (log_id, action, user_id) VALUES (15, 'Ground Turnaround Sub-Task Closed', 16) ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (log_id, action, user_id) VALUES (16, 'User Login Succeeded', 17) ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (log_id, action, user_id) VALUES (17, 'Gate Assignment Modified', 18) ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (log_id, action, user_id) VALUES (18, 'Flight Status Updated to BOARDING', 19) ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (log_id, action, user_id) VALUES (19, 'Refueling Density Transaction Completed', 20) ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (log_id, action, user_id) VALUES (20, 'Ground Turnaround Sub-Task Closed', 21) ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (log_id, action, user_id) VALUES (21, 'User Login Succeeded', 22) ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (log_id, action, user_id) VALUES (22, 'Gate Assignment Modified', 23) ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (log_id, action, user_id) VALUES (23, 'Flight Status Updated to BOARDING', 24) ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (log_id, action, user_id) VALUES (24, 'Refueling Density Transaction Completed', 25) ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (log_id, action, user_id) VALUES (25, 'Ground Turnaround Sub-Task Closed', 26) ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (log_id, action, user_id) VALUES (26, 'User Login Succeeded', 27) ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (log_id, action, user_id) VALUES (27, 'Gate Assignment Modified', 28) ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (log_id, action, user_id) VALUES (28, 'Flight Status Updated to BOARDING', 29) ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (log_id, action, user_id) VALUES (29, 'Refueling Density Transaction Completed', 30) ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (log_id, action, user_id) VALUES (30, 'Ground Turnaround Sub-Task Closed', 31) ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (log_id, action, user_id) VALUES (31, 'User Login Succeeded', 32) ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (log_id, action, user_id) VALUES (32, 'Gate Assignment Modified', 33) ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (log_id, action, user_id) VALUES (33, 'Flight Status Updated to BOARDING', 34) ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (log_id, action, user_id) VALUES (34, 'Refueling Density Transaction Completed', 35) ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (log_id, action, user_id) VALUES (35, 'Ground Turnaround Sub-Task Closed', 36) ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (log_id, action, user_id) VALUES (36, 'User Login Succeeded', 37) ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (log_id, action, user_id) VALUES (37, 'Gate Assignment Modified', 38) ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (log_id, action, user_id) VALUES (38, 'Flight Status Updated to BOARDING', 39) ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (log_id, action, user_id) VALUES (39, 'Refueling Density Transaction Completed', 40) ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (log_id, action, user_id) VALUES (40, 'Ground Turnaround Sub-Task Closed', 41) ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (log_id, action, user_id) VALUES (41, 'User Login Succeeded', 42) ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (log_id, action, user_id) VALUES (42, 'Gate Assignment Modified', 43) ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (log_id, action, user_id) VALUES (43, 'Flight Status Updated to BOARDING', 44) ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (log_id, action, user_id) VALUES (44, 'Refueling Density Transaction Completed', 45) ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (log_id, action, user_id) VALUES (45, 'Ground Turnaround Sub-Task Closed', 46) ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (log_id, action, user_id) VALUES (46, 'User Login Succeeded', 47) ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (log_id, action, user_id) VALUES (47, 'Gate Assignment Modified', 48) ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (log_id, action, user_id) VALUES (48, 'Flight Status Updated to BOARDING', 49) ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (log_id, action, user_id) VALUES (49, 'Refueling Density Transaction Completed', 50) ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (log_id, action, user_id) VALUES (50, 'Ground Turnaround Sub-Task Closed', 1) ON CONFLICT DO NOTHING;
