import os

# 1. WRITE MARKDOWN FILE
md_dir = "/Users/krish/Desktop/Software Engineering/Mini Project/documentation/MD/database_creation"
os.makedirs(md_dir, exist_ok=True)
md_path = os.path.join(md_dir, "information_package_matrix.md")

md_content = """# AIRPORT OPERATIONS COORDINATION SYSTEM (AOCS)
## Step 2: Information Package Diagram & Data Warehouse Requirements Matrix

---

### Executive Overview & Analytical Scope
The **Information Package Diagram** defines the conceptual requirements for the AOCS Data Warehouse prior to building the Star Schema. In accordance with the **Ralph Kimball Data Warehouse Lifecycle**, this document outlines the analytical subject area, conformed dimensions, drill-down hierarchies, and quantitative fact metrics (KPIs).

To prevent information loss across the **16 operational entities** defined in the Peter Chen ERD, this model establishes **10 Dedicated Dimensions** ensuring 100% coverage of flight, infrastructure, personnel, passenger, and ground logistics data.

---

## SECTION 1: BUSINESS SUBJECT AREA & GRAIN

* **Subject Area**: `Flight Turnaround & Operational Performance Analytics`
* **Business Objective**: Evaluate operational efficiency, quantify turnaround delays, measure ground crew productivity, track resource utilization (gates/runways), and optimize fuel/cargo throughput.
* **Fact Table Grain**: **Atomic Grain — One record per individual flight turnaround event.**

---

## SECTION 2: THE 10 CONFORMED DIMENSIONS & HIERARCHIES

The 10 dimensions provide comprehensive slicing and dicing capabilities across all operational facets:

| Dimension Name | Source ERD Entities | Drill-Down Hierarchy (Highest to Lowest Grain) | Key Attributes |
|---|---|---|---|
| **`DIM_TIME`** | System Clock / Calendar | `Year` ➔ `Quarter` ➔ `Month` ➔ `Week` ➔ `Date` ➔ `Shift` (Morning/Afternoon/Night) ➔ `Peak Hour` | `time_key`, `full_date`, `day_of_week`, `is_holiday` |
| **`DIM_FLIGHT`** | `FLIGHTS` | `Airline / Carrier` ➔ `Flight Type` (Pax/Cargo, Domestic/Intl) ➔ `Flight Number` ➔ `Flight ID` | `flight_key`, `flight_number`, `carrier_code`, `status` |
| **`DIM_AIRCRAFT`** | `AIRCRAFT` | `Manufacturer` (Boeing/Airbus) ➔ `Model Series` ➔ `Registration Number` ➔ `Aircraft ID` | `aircraft_key`, `registration_no`, `model`, `capacity` |
| **`DIM_GATE`** | `GATES` | `Airport Terminal` ➔ `Concourse / Zone` ➔ `Gate Type` ➔ `Gate Number` ➔ `Gate ID` | `gate_key`, `gate_number`, `terminal_code`, `zone` |
| **`DIM_RUNWAY`** | `RUNWAYS` | `Airside Zone` ➔ `Surface Type` ➔ `Length Category` ➔ `Runway Code` ➔ `Runway ID` | `runway_key`, `runway_code`, `length_meters`, `surface` |
| **`DIM_USER`** | `USERS` | `Employment Status` ➔ `Staff User Name` ➔ `Username` ➔ `User ID` | `user_key`, `username`, `full_name`, `phone_number` |
| **`DIM_DEPARTMENT`** | `DEPARTMENTS` | `Department Type` ➔ `Department Name` ➔ `Manager` ➔ `Department ID` | `department_key`, `department_name`, `manager` |
| **`DIM_ROLE`** | `ROLES` | `Access Security Tier` ➔ `Role Category` ➔ `Role Name` ➔ `Role ID` | `role_key`, `role_name`, `access_tier` |
| **`DIM_PASSENGER`** | `PASSENGERS`, `LOUNGE_VISITS` | `VIP Level` ➔ `Passport Country` ➔ `Lounge Location` ➔ `Passport Number` ➔ `Passenger ID` | `passenger_key`, `passport_no`, `lounge_used` |
| **`DIM_LOGISTICS`** | `FUEL_LOGS`, `CARGO_MANIFESTS`, `BAGGAGE_CAROUSELS` | `Logistics Category` ➔ `Cargo Container Type` / `Fuel Grade` / `Carousel Terminal` ➔ `Resource ID` | `logistics_key`, `container_id`, `fuel_density`, `carousel_no` |

---

## SECTION 3: FACT METRICS & MEASURES (QUANTITATIVE KPIS)

The measures stored at the center of the Information Package quantify turnaround performance:

### 1. Turnaround Duration Metrics
* **`planned_turnaround_mins`**: Scheduled target duration for turnaround.
* **`actual_turnaround_mins`**: Realized elapsed time from gate arrival to pushback.
* **`turnaround_variance_mins`**: Difference (`actual_turnaround_mins - planned_turnaround_mins`).
* **`turnaround_efficiency_pct`**: Ratio of target to actual turnaround (`(planned / actual) * 100`).

### 2. Delay & Bottleneck Metrics
* **`total_delay_mins`**: Total accumulated delay time for the flight.
* **`ground_delay_mins`**: Portion of delay incurred during ground turnaround.
* **`air_delay_mins`**: Portion of delay incurred during airborne holding/approach.
* **`delay_incident_count`**: Count of distinct logged delay incidents (`DELAY_LOGS`).

### 3. Logistics & Resource Volume Metrics
* **`passenger_count`**: Total boarded passengers on the flight.
* **`lounge_visit_count`**: Total executive lounge visits generated by the flight passengers.
* **`baggage_units_processed`**: Total checked luggage items delivered to carousels.
* **`cargo_weight_kg`**: Total weight of cargo containers loaded.
* **`fuel_delivered_liters`**: Total volume of aviation fuel pumped.

### 4. Staff & Task Execution Metrics
* **`total_tasks_assigned`**: Count of ground turnaround sub-tasks created.
* **`tasks_completed_on_time`**: Count of sub-tasks finished within SLA window.
* **`task_delay_duration_mins`**: Cumulative delay time across sub-tasks.

---

## SECTION 4: DATA WAREHOUSE BUS MATRIX

| Business Process / Event | `DIM_TIME` | `DIM_FLIGHT` | `DIM_AIRCRAFT` | `DIM_GATE` | `DIM_RUNWAY` | `DIM_USER` | `DIM_DEPARTMENT` | `DIM_ROLE` | `DIM_PASSENGER` | `DIM_LOGISTICS` |
|---|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| **Flight Turnaround Analytics** | X | X | X | X | X | X | X | X | X | X |
| **Ground Task Performance** | X | X | - | X | - | X | X | X | - | X |
| **Logistics & Fuel Audit** | X | X | X | - | - | X | X | - | - | X |
| **Passenger & Lounge Services** | X | X | - | X | - | - | - | - | X | X |

---
*Author: Antigravity Agent (Google Deepmind) | Project: Airport Operations Coordination System (AOCS)*
"""

with open(md_path, "w", encoding="utf-8") as f:
    f.write(md_content)

print(f"Successfully created {md_path}")


# 2. WRITE DRAW.IO XML FILE (NO COLORS, MONOCHROME, CLEAN GRID)
db_dir = "/Users/krish/Desktop/Software Engineering/Mini Project/db"
os.makedirs(db_dir, exist_ok=True)
drawio_path = os.path.join(db_dir, "AOCS Information Package.drawio.xml")

xml_content = """<?xml version="1.0" encoding="UTF-8"?>
<mxfile host="Electron">
  <diagram name="AOCS-Information-Package-Matrix" id="aocs-ipm-01">
    <mxGraphModel dx="2400" dy="1600" grid="1" gridSize="10" guides="1" tooltips="1" connect="1" arrows="1" fold="1" page="1" pageScale="1" pageWidth="2400" pageHeight="1600" math="0" shadow="0">
      <root>
        <mxCell id="0" />
        <mxCell id="1" parent="0" />

        <!-- ============================================================ -->
        <!-- MATRIX MAIN CONTAINER / BORDER                               -->
        <!-- ============================================================ -->
        
        <!-- TITLE BANNER -->
        <mxCell id="hdr_title" value="&lt;b style=&quot;font-size: 16px;&quot;&gt;AIRPORT OPERATIONS COORDINATION SYSTEM (AOCS)&lt;/b&gt;&lt;br&gt;&lt;span style=&quot;font-size: 13px;&quot;&gt;Information Package Diagram (Data Warehouse Dimensional Analytics Matrix)&lt;/span&gt;" style="rounded=0;whiteSpace=wrap;html=1;fontStyle=1;fontSize=14;fillColor=none;strokeColor=default;fontColor=default;" vertex="1" parent="1">
          <mxGeometry x="50" y="30" width="2085" height="50" as="geometry" />
        </mxCell>

        <!-- SUBJECT AREA BANNER -->
        <mxCell id="hdr_subject" value="&lt;b&gt;BUSINESS SUBJECT AREA:&lt;/b&gt; Flight Turnaround &amp;amp; Operational Performance Analytics &amp;nbsp;&amp;nbsp;&amp;nbsp;|&amp;nbsp;&amp;nbsp;&amp;nbsp; &lt;b&gt;GRAIN:&lt;/b&gt; Atomic — One record per individual flight turnaround event" style="rounded=0;whiteSpace=wrap;html=1;fontStyle=0;fontSize=11;fillColor=none;strokeColor=default;fontColor=default;" vertex="1" parent="1">
          <mxGeometry x="50" y="90" width="2085" height="35" as="geometry" />
        </mxCell>

        <!-- ============================================================ -->
        <!-- 10 DIMENSION COLUMNS (x=50 to x=2135, width=195 each, gap=15) -->
        <!-- ============================================================ -->

        <!-- DIM 1: TIME -->
        <mxCell id="dim1_hdr" value="&lt;b style=&quot;font-size: 12px;&quot;&gt;DIM_TIME&lt;/b&gt;&lt;br&gt;&lt;span style=&quot;font-size: 9px;&quot;&gt;(Calendar &amp;amp; Shift)&lt;/span&gt;" style="rounded=0;whiteSpace=wrap;html=1;fontStyle=1;fillColor=none;strokeColor=default;fontColor=default;" vertex="1" parent="1">
          <mxGeometry x="50" y="135" width="195" height="45" as="geometry" />
        </mxCell>
        <mxCell id="dim1_body" value="Year&#10;└── Quarter&#10;    └── Month / Week&#10;        └── Date&#10;            └── Shift (Morn/Aft/Nite)&#10;                └── Peak Hour&#10;&#10;──────────────────────&#10;[Keys &amp; Attributes]&#10;• time_key (PK)&#10;• full_date&#10;• day_of_week&#10;• is_holiday_flag" style="rounded=0;whiteSpace=wrap;html=1;align=left;verticalAlign=top;spacingLeft=8;spacingTop=8;fontSize=10;fillColor=none;strokeColor=default;fontColor=default;" vertex="1" parent="1">
          <mxGeometry x="50" y="185" width="195" height="340" as="geometry" />
        </mxCell>

        <!-- DIM 2: FLIGHT -->
        <mxCell id="dim2_hdr" value="&lt;b style=&quot;font-size: 12px;&quot;&gt;DIM_FLIGHT&lt;/b&gt;&lt;br&gt;&lt;span style=&quot;font-size: 9px;&quot;&gt;(FLIGHTS Entity)&lt;/span&gt;" style="rounded=0;whiteSpace=wrap;html=1;fontStyle=1;fillColor=none;strokeColor=default;fontColor=default;" vertex="1" parent="1">
          <mxGeometry x="260" y="135" width="195" height="45" as="geometry" />
        </mxCell>
        <mxCell id="dim2_body" value="Airline / Carrier&#10;└── Flight Category (Pax/Cargo)&#10;    └── Route Type (Dom/Intl)&#10;        └── Flight Number&#10;            └── Flight ID&#10;&#10;──────────────────────&#10;[Keys &amp; Attributes]&#10;• flight_key (PK)&#10;• flight_number&#10;• carrier_code&#10;• flight_status" style="rounded=0;whiteSpace=wrap;html=1;align=left;verticalAlign=top;spacingLeft=8;spacingTop=8;fontSize=10;fillColor=none;strokeColor=default;fontColor=default;" vertex="1" parent="1">
          <mxGeometry x="260" y="185" width="195" height="340" as="geometry" />
        </mxCell>

        <!-- DIM 3: AIRCRAFT -->
        <mxCell id="dim3_hdr" value="&lt;b style=&quot;font-size: 12px;&quot;&gt;DIM_AIRCRAFT&lt;/b&gt;&lt;br&gt;&lt;span style=&quot;font-size: 9px;&quot;&gt;(AIRCRAFT Entity)&lt;/span&gt;" style="rounded=0;whiteSpace=wrap;html=1;fontStyle=1;fillColor=none;strokeColor=default;fontColor=default;" vertex="1" parent="1">
          <mxGeometry x="470" y="135" width="195" height="45" as="geometry" />
        </mxCell>
        <mxCell id="dim3_body" value="Manufacturer (Boeing/Airbus)&#10;└── Aircraft Model Series&#10;    └── Registration Number&#10;        └── Aircraft ID&#10;&#10;──────────────────────&#10;[Keys &amp; Attributes]&#10;• aircraft_key (PK)&#10;• registration_number&#10;• model_type&#10;• seating_capacity" style="rounded=0;whiteSpace=wrap;html=1;align=left;verticalAlign=top;spacingLeft=8;spacingTop=8;fontSize=10;fillColor=none;strokeColor=default;fontColor=default;" vertex="1" parent="1">
          <mxGeometry x="470" y="185" width="195" height="340" as="geometry" />
        </mxCell>

        <!-- DIM 4: GATE -->
        <mxCell id="dim4_hdr" value="&lt;b style=&quot;font-size: 12px;&quot;&gt;DIM_GATE&lt;/b&gt;&lt;br&gt;&lt;span style=&quot;font-size: 9px;&quot;&gt;(GATES Entity)&lt;/span&gt;" style="rounded=0;whiteSpace=wrap;html=1;fontStyle=1;fillColor=none;strokeColor=default;fontColor=default;" vertex="1" parent="1">
          <mxGeometry x="680" y="135" width="195" height="45" as="geometry" />
        </mxCell>
        <mxCell id="dim4_body" value="Airport Terminal&#10;└── Concourse / Zone&#10;    └── Gate Type (Contact/Remote)&#10;        └── Gate Number&#10;            └── Gate ID&#10;&#10;──────────────────────&#10;[Keys &amp; Attributes]&#10;• gate_key (PK)&#10;• gate_number&#10;• terminal_code&#10;• concourse_zone" style="rounded=0;whiteSpace=wrap;html=1;align=left;verticalAlign=top;spacingLeft=8;spacingTop=8;fontSize=10;fillColor=none;strokeColor=default;fontColor=default;" vertex="1" parent="1">
          <mxGeometry x="680" y="185" width="195" height="340" as="geometry" />
        </mxCell>

        <!-- DIM 5: RUNWAY -->
        <mxCell id="dim5_hdr" value="&lt;b style=&quot;font-size: 12px;&quot;&gt;DIM_RUNWAY&lt;/b&gt;&lt;br&gt;&lt;span style=&quot;font-size: 9px;&quot;&gt;(RUNWAYS Entity)&lt;/span&gt;" style="rounded=0;whiteSpace=wrap;html=1;fontStyle=1;fillColor=none;strokeColor=default;fontColor=default;" vertex="1" parent="1">
          <mxGeometry x="890" y="135" width="195" height="45" as="geometry" />
        </mxCell>
        <mxCell id="dim5_body" value="Airside Sector&#10;└── Surface Type&#10;    └── Length Category&#10;        └── Runway Code&#10;            └── Runway ID&#10;&#10;──────────────────────&#10;[Keys &amp; Attributes]&#10;• runway_key (PK)&#10;• runway_code&#10;• length_meters&#10;• surface_type" style="rounded=0;whiteSpace=wrap;html=1;align=left;verticalAlign=top;spacingLeft=8;spacingTop=8;fontSize=10;fillColor=none;strokeColor=default;fontColor=default;" vertex="1" parent="1">
          <mxGeometry x="890" y="185" width="195" height="340" as="geometry" />
        </mxCell>

        <!-- DIM 6: USER -->
        <mxCell id="dim6_hdr" value="&lt;b style=&quot;font-size: 12px;&quot;&gt;DIM_USER&lt;/b&gt;&lt;br&gt;&lt;span style=&quot;font-size: 9px;&quot;&gt;(USERS Entity)&lt;/span&gt;" style="rounded=0;whiteSpace=wrap;html=1;fontStyle=1;fillColor=none;strokeColor=default;fontColor=default;" vertex="1" parent="1">
          <mxGeometry x="1100" y="135" width="195" height="45" as="geometry" />
        </mxCell>
        <mxCell id="dim6_body" value="Employment Status&#10;└── Staff Full Name&#10;    └── Username&#10;        └── User ID&#10;&#10;──────────────────────&#10;[Keys &amp; Attributes]&#10;• user_key (PK)&#10;• username&#10;• full_name&#10;• phone_number" style="rounded=0;whiteSpace=wrap;html=1;align=left;verticalAlign=top;spacingLeft=8;spacingTop=8;fontSize=10;fillColor=none;strokeColor=default;fontColor=default;" vertex="1" parent="1">
          <mxGeometry x="1100" y="185" width="195" height="340" as="geometry" />
        </mxCell>

        <!-- DIM 7: DEPARTMENT -->
        <mxCell id="dim7_hdr" value="&lt;b style=&quot;font-size: 12px;&quot;&gt;DIM_DEPARTMENT&lt;/b&gt;&lt;br&gt;&lt;span style=&quot;font-size: 9px;&quot;&gt;(DEPARTMENTS Entity)&lt;/span&gt;" style="rounded=0;whiteSpace=wrap;html=1;fontStyle=1;fillColor=none;strokeColor=default;fontColor=default;" vertex="1" parent="1">
          <mxGeometry x="1310" y="135" width="195" height="45" as="geometry" />
        </mxCell>
        <mxCell id="dim7_body" value="Department Category&#10;└── Department Name&#10;    └── Manager / Supervisor&#10;        └── Department ID&#10;&#10;──────────────────────&#10;[Keys &amp; Attributes]&#10;• department_key (PK)&#10;• department_name&#10;• manager_name&#10;• number_of_staff" style="rounded=0;whiteSpace=wrap;html=1;align=left;verticalAlign=top;spacingLeft=8;spacingTop=8;fontSize=10;fillColor=none;strokeColor=default;fontColor=default;" vertex="1" parent="1">
          <mxGeometry x="1310" y="185" width="195" height="340" as="geometry" />
        </mxCell>

        <!-- DIM 8: ROLE -->
        <mxCell id="dim8_hdr" value="&lt;b style=&quot;font-size: 12px;&quot;&gt;DIM_ROLE&lt;/b&gt;&lt;br&gt;&lt;span style=&quot;font-size: 9px;&quot;&gt;(ROLES Entity)&lt;/span&gt;" style="rounded=0;whiteSpace=wrap;html=1;fontStyle=1;fillColor=none;strokeColor=default;fontColor=default;" vertex="1" parent="1">
          <mxGeometry x="1520" y="135" width="195" height="45" as="geometry" />
        </mxCell>
        <mxCell id="dim8_body" value="Access Security Tier&#10;└── Operational Clearance&#10;    └── Role Name&#10;        └── Role ID&#10;&#10;──────────────────────&#10;[Keys &amp; Attributes]&#10;• role_key (PK)&#10;• role_name&#10;• clearance_level" style="rounded=0;whiteSpace=wrap;html=1;align=left;verticalAlign=top;spacingLeft=8;spacingTop=8;fontSize=10;fillColor=none;strokeColor=default;fontColor=default;" vertex="1" parent="1">
          <mxGeometry x="1520" y="185" width="195" height="340" as="geometry" />
        </mxCell>

        <!-- DIM 9: PASSENGER -->
        <mxCell id="dim9_hdr" value="&lt;b style=&quot;font-size: 12px;&quot;&gt;DIM_PASSENGER&lt;/b&gt;&lt;br&gt;&lt;span style=&quot;font-size: 9px;&quot;&gt;(PASSENGERS &amp;amp; LOUNGE)&lt;/span&gt;" style="rounded=0;whiteSpace=wrap;html=1;fontStyle=1;fillColor=none;strokeColor=default;fontColor=default;" vertex="1" parent="1">
          <mxGeometry x="1730" y="135" width="195" height="45" as="geometry" />
        </mxCell>
        <mxCell id="dim9_body" value="Passport Country&#10;└── VIP Tier Level&#10;    └── Executive Lounge Used&#10;        └── Passport Number&#10;            └── Passenger ID&#10;&#10;──────────────────────&#10;[Keys &amp; Attributes]&#10;• passenger_key (PK)&#10;• passport_number&#10;• lounge_name&#10;• vip_level" style="rounded=0;whiteSpace=wrap;html=1;align=left;verticalAlign=top;spacingLeft=8;spacingTop=8;fontSize=10;fillColor=none;strokeColor=default;fontColor=default;" vertex="1" parent="1">
          <mxGeometry x="1730" y="185" width="195" height="340" as="geometry" />
        </mxCell>

        <!-- DIM 10: LOGISTICS -->
        <mxCell id="dim10_hdr" value="&lt;b style=&quot;font-size: 12px;&quot;&gt;DIM_LOGISTICS&lt;/b&gt;&lt;br&gt;&lt;span style=&quot;font-size: 9px;&quot;&gt;(FUEL, CARGO, BAGGAGE)&lt;/span&gt;" style="rounded=0;whiteSpace=wrap;html=1;fontStyle=1;fillColor=none;strokeColor=default;fontColor=default;" vertex="1" parent="1">
          <mxGeometry x="1940" y="135" width="195" height="45" as="geometry" />
        </mxCell>
        <mxCell id="dim10_body" value="Logistics Resource Type&#10;├── Fuel Grade / Density&#10;├── Cargo Container Type&#10;└── Carousel Terminal&#10;&#10;──────────────────────&#10;[Keys &amp; Attributes]&#10;• logistics_key (PK)&#10;• container_id&#10;• fuel_density&#10;• carousel_id" style="rounded=0;whiteSpace=wrap;html=1;align=left;verticalAlign=top;spacingLeft=8;spacingTop=8;fontSize=10;fillColor=none;strokeColor=default;fontColor=default;" vertex="1" parent="1">
          <mxGeometry x="1940" y="185" width="195" height="340" as="geometry" />
        </mxCell>


        <!-- ============================================================ -->
        <!-- BOTTOM FACT METRICS / MEASURES ROW                           -->
        <!-- ============================================================ -->

        <mxCell id="fact_hdr" value="&lt;b style=&quot;font-size: 13px;&quot;&gt;FACT METRICS &amp;amp; MEASURES (QUANTITATIVE ANALYTICAL KPIS - FACT_FLIGHT_TURNAROUND)&lt;/b&gt;" style="rounded=0;whiteSpace=wrap;html=1;fontStyle=1;fontSize=12;fillColor=none;strokeColor=default;fontColor=default;" vertex="1" parent="1">
          <mxGeometry x="50" y="535" width="2085" height="35" as="geometry" />
        </mxCell>
        
        <mxCell id="fact_body" value="&lt;table border=&quot;0&quot; width=&quot;100%&quot; style=&quot;font-size: 10px;&quot;&gt;&lt;tr&gt;&lt;td width=&quot;25%&quot; valign=&quot;top&quot;&gt;&lt;b&gt;⏱️ Turnaround Duration Metrics:&lt;/b&gt;&lt;br&gt;• planned_turnaround_mins&lt;br&gt;• actual_turnaround_mins&lt;br&gt;• turnaround_variance_mins&lt;br&gt;• turnaround_efficiency_pct&lt;/td&gt;&lt;td width=&quot;25%&quot; valign=&quot;top&quot;&gt;&lt;b&gt;⚠️ Delay &amp;amp; Bottleneck Metrics:&lt;/b&gt;&lt;br&gt;• total_delay_mins&lt;br&gt;• ground_delay_mins&lt;br&gt;• air_delay_mins&lt;br&gt;• delay_incident_count&lt;/td&gt;&lt;td width=&quot;25%&quot; valign=&quot;top&quot;&gt;&lt;b&gt;📦 Logistics Volume &amp;amp; Throughput:&lt;/b&gt;&lt;br&gt;• passenger_count (Boarded)&lt;br&gt;• lounge_visit_count&lt;br&gt;• baggage_units_processed&lt;br&gt;• cargo_weight_kg&lt;br&gt;• fuel_delivered_liters&lt;/td&gt;&lt;td width=&quot;25%&quot; valign=&quot;top&quot;&gt;&lt;b&gt;🛠️ Staff &amp;amp; Task Performance:&lt;/b&gt;&lt;br&gt;• total_tasks_assigned&lt;br&gt;• tasks_completed_on_time&lt;br&gt;• task_delay_duration_mins&lt;br&gt;• staff_productivity_rate&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;" style="rounded=0;whiteSpace=wrap;html=1;align=left;verticalAlign=top;spacingLeft=10;spacingTop=10;fontSize=10;fillColor=none;strokeColor=default;fontColor=default;" vertex="1" parent="1">
          <mxGeometry x="50" y="570" width="2085" height="120" as="geometry" />
        </mxCell>

      </root>
    </mxGraphModel>
  </diagram>
</mxfile>
"""

with open(drawio_path, "w", encoding="utf-8") as f:
    f.write(xml_content)

print(f"Successfully created {drawio_path}")

# Also copy to Information-Package.xml in db/
sync_path = os.path.join(db_dir, "Information-Package.xml")
with open(sync_path, "w", encoding="utf-8") as f:
    f.write(xml_content)

print(f"Successfully synced to {sync_path}")
